export type WordEntry = {
  word: string;
  label: string;
  country: string;
  wikipedia: string;
  hint: string;
};

export const WORDS: WordEntry[] = [
  {
    word: "santiago",
    label: "Santiago",
    country: "Chile",
    wikipedia: "Santiago de Chile",
    hint: "Un apostol le presta su nombre.",
  },
  {
    word: "sofia",
    label: "Sofía",
    country: "Bulgaria",
    wikipedia: "Sofía (Bulgaria)",
    hint: "En griego antiguo significa sabiduria.",
  },
  {
    word: "abuya",
    label: "Abuya",
    country: "Nigeria",
    wikipedia: "Abuya",
    hint: "Reemplazó a la mayor ciudad del pais como sede del gobierno en 1991.",
  },
  {
    word: "montevideo",
    label: "Montevideo",
    country: "Uruguay",
    wikipedia: "Montevideo",
    hint: "Un vigia habria visto un monte al fondo.",
  },
  {
    word: "moscu",
    label: "Moscú",
    country: "Rusia",
    wikipedia: "Moscú",
    hint: "Cinco cupulas de colores decoran su plaza principal.",
  },
  {
    word: "londres",
    label: "Londres",
    country: "Reino Unido",
    wikipedia: "Londres",
    hint: "Un puente muy fotografiado la parte en dos sobre el Tamesis.",
  },
  {
    word: "ottawa",
    label: "Ottawa",
    country: "Canadá",
    wikipedia: "Ottawa",
    hint: "No es la mas grande ni la mas conocida, pero manda en su pais.",
  },
  {
    word: "lima",
    label: "Lima",
    country: "Perú",
    wikipedia: "Lima",
    hint: "Comparte nombre con un citrico verde.",
  },
  {
    word: "roma",
    label: "Roma",
    country: "Italia",
    wikipedia: "Roma",
    hint: "Palindromo de un sentimiento.",
  },
  {
    word: "lisboa",
    label: "Lisboa",
    country: "Portugal",
    wikipedia: "Lisboa",
    hint: "El fado nacio en sus tabernas.",
  },
  {
    word: "tokio",
    label: "Tokio",
    country: "Japón",
    wikipedia: "Tokio",
    hint: "Antes se llamaba Edo.",
  },
  {
    word: "berlin",
    label: "Berlín",
    country: "Alemania",
    wikipedia: "Berlín",
    hint: "Un muro la dividio hasta 1989.",
  },
  {
    word: "paris",
    label: "París",
    country: "Francia",
    wikipedia: "París",
    hint: "Un principe troyano rapto a una reina helena.",
  },
  {
    word: "madrid",
    label: "Madrid",
    country: "España",
    wikipedia: "Madrid",
    hint: "Un oso observa un arbol de frutos rojos.",
  },
  {
    word: "pekin",
    label: "Pekín",
    country: "China",
    wikipedia: "Pekín",
    hint: "Su pato asado es un plato de fama mundial.",
  },
  {
    word: "canberra",
    label: "Canberra",
    country: "Australia",
    wikipedia: "Canberra",
    hint: "Fue elegida para no favorecer a Sidney ni Melbourne.",
  },
  {
    word: "nairobi",
    label: "Nairobi",
    country: "Kenia",
    wikipedia: "Nairobi",
    hint: "En suajili quiere decir 'aguas frescas'.",
  },
  {
    word: "bangkok",
    label: "Bangkok",
    country: "Tailandia",
    wikipedia: "Bangkok",
    hint: "Ciudad de templos dorados y trafico eterno.",
  },
  {
    word: "varsovia",
    label: "Varsovia",
    country: "Polonia",
    wikipedia: "Varsovia",
    hint: "Renacio de sus ruinas, ladrillo a ladrillo, tras la guerra.",
  },
  {
    word: "atenas",
    label: "Atenas",
    country: "Grecia",
    wikipedia: "Atenas",
    hint: "Le debe el nombre a la diosa de la sabiduria.",
  },
  {
    word: "budapest",
    label: "Budapest",
    country: "Hungría",
    wikipedia: "Budapest",
    hint: "Dos ciudades unidas por puentes sobre el Danubio.",
  },
  {
    word: "viena",
    label: "Viena",
    country: "Austria",
    wikipedia: "Viena",
    hint: "El vals nacio en sus salones.",
  },
  {
    word: "bruselas",
    label: "Bruselas",
    country: "Bélgica",
    wikipedia: "Bruselas",
    hint: "Un niño de bronce orina en su fuente mas conocida.",
  },
  {
    word: "amsterdam",
    label: "Ámsterdam",
    country: "Países Bajos",
    wikipedia: "Ámsterdam",
    hint: "Sus canales dibujan un semicirculo desde el centro.",
  },
  {
    word: "oslo",
    label: "Oslo",
    country: "Noruega",
    wikipedia: "Oslo",
    hint: "Aqui se entrega el Nobel de la Paz.",
  },
  {
    word: "estocolmo",
    label: "Estocolmo",
    country: "Suecia",
    wikipedia: "Estocolmo",
    hint: "Un sindrome psicologico lleva su nombre.",
  },
  {
    word: "helsinki",
    label: "Helsinki",
    country: "Finlandia",
    wikipedia: "Helsinki",
    hint: "Una fortaleza sueca custodia su bahia.",
  },
  {
    word: "dublin",
    label: "Dublín",
    country: "Irlanda",
    wikipedia: "Dublín",
    hint: "James Joyce le dedico un libro de cuentos.",
  },
  {
    word: "praga",
    label: "Praga",
    country: "Chequia",
    wikipedia: "Praga",
    hint: "Un reloj astronomico atrae multitudes cada hora.",
  },
  {
    word: "bucarest",
    label: "Bucarest",
    country: "Rumanía",
    wikipedia: "Bucarest",
    hint: "Contiene el segundo edificio administrativo mas grande del planeta.",
  },
  {
    word: "ankara",
    label: "Ankara",
    country: "Turquía",
    wikipedia: "Ankara",
    hint: "Estambul es mas famosa, pero el gobierno esta aqui.",
  },
  {
    word: "seul",
    label: "Seúl",
    country: "Corea del Sur",
    wikipedia: "Seúl",
    hint: "El rio Han la parte en dos.",
  },
  {
    word: "yakarta",
    label: "Yakarta",
    country: "Indonesia",
    wikipedia: "Yakarta",
    hint: "Se planea mudarla a Borneo porque se hunde.",
  },
  {
    word: "islamabad",
    label: "Islamabad",
    country: "Pakistán",
    wikipedia: "Islamabad",
    hint: "Su nombre contiene el de una religion.",
  },
  {
    word: "bagdad",
    label: "Bagdad",
    country: "Iraq",
    wikipedia: "Bagdad",
    hint: "Escenario de las Mil y una Noches.",
  },
  {
    word: "teheran",
    label: "Teherán",
    country: "Irán",
    wikipedia: "Teherán",
    hint: "Los montes Elburz la abrigan al norte.",
  },
  {
    word: "riad",
    label: "Riad",
    country: "Arabia Saudita",
    wikipedia: "Riad",
    hint: "En medio de la peninsula arabiga.",
  },
  {
    word: "doha",
    label: "Doha",
    country: "Catar",
    wikipedia: "Doha",
    hint: "Albergo el Mundial de futbol de 2022.",
  },
  {
    word: "baku",
    label: "Bakú",
    country: "Azerbaiyán",
    wikipedia: "Bakú",
    hint: "A orillas del Caspio, con torres en forma de llama.",
  },
  {
    word: "tiflis",
    label: "Tiflis",
    country: "Georgia",
    wikipedia: "Tiflis",
    hint: "Sus aguas termales sulfurosas perfuman el casco antiguo.",
  },
  {
    word: "erevan",
    label: "Ereván",
    country: "Armenia",
    wikipedia: "Ereván",
    hint: "Mira al monte Ararat, aunque no le pertenece.",
  },
  {
    word: "minsk",
    label: "Minsk",
    country: "Bielorrusia",
    wikipedia: "Minsk",
    hint: "La capital menos conocida del bloque postsovietico.",
  },
  {
    word: "kiev",
    label: "Kiev",
    country: "Ucrania",
    wikipedia: "Kiev",
    hint: "Origen de la Rus, madre de otras ciudades eslavas.",
  },
  {
    word: "chisinau",
    label: "Chisináu",
    country: "Moldavia",
    wikipedia: "Chisináu",
    hint: "Capital de una tierra de vinos entre dos vecinos mayores.",
  },
  {
    word: "tirana",
    label: "Tirana",
    country: "Albania",
    wikipedia: "Tirana",
    hint: "Enver Hoxha llenó de bunkers el pais que la rodea.",
  },
  {
    word: "skopie",
    label: "Skopie",
    country: "Macedonia del Norte",
    wikipedia: "Skopie",
    hint: "Aqui nacio la Madre Teresa.",
  },
  {
    word: "sarajevo",
    label: "Sarajevo",
    country: "Bosnia y Herzegovina",
    wikipedia: "Sarajevo",
    hint: "El asesinato de un archiduque austriaco desato una guerra mundial aqui.",
  },
  {
    word: "belgrado",
    label: "Belgrado",
    country: "Serbia",
    wikipedia: "Belgrado",
    hint: "Su nombre significa 'ciudad blanca'.",
  },
  {
    word: "zagreb",
    label: "Zagreb",
    country: "Croacia",
    wikipedia: "Zagreb",
    hint: "Su casco medieval se divide en parte Alta y Baja.",
  },
];
