-- ============================================================
-- SEED: palabras famosas N5 (3 palabras por kanji, 100 kanjis)
-- ============================================================
--
-- Companion del seed_kanji_n5. Se agregan palabras comunes (vocabulario
-- N5-N4 tipico) para cada kanji cargado en la BDD como nivel n5.
--
-- Formato de cada fila (caracter, palabra, furigana, traduccion):
--   caracter    -> kanji origen (varchar 1, se usa para joinear con kanji.id)
--   palabra     -> palabra escrita con kanji (o mixta con hiragana)
--   furigana    -> lectura COMPLETA de la palabra en hiragana (no solo
--                  la parte del kanji)
--   traduccion  -> significado en español
--
-- Idempotente: primero borra todas las palabras existentes de los kanjis
-- cargados como n5, luego inserta el listado completo. Correr las veces
-- que sea necesario sin dejar duplicados.
--
-- NOTA: el DELETE solo afecta a palabras cuyo kanji_id pertenece a
-- nivel = 'n5'. Palabras de kanjis n4 u otros niveles no se tocan.
-- --------------------------------------------------------------

DELETE FROM palabras_famosas
WHERE kanji_id IN (
  SELECT id FROM kanji WHERE nivel = 'n5'::nivel_jlpt
);

INSERT INTO palabras_famosas (kanji_id, palabra, furigana, traduccion)
SELECT k.id, v.palabra, v.furigana, v.traduccion
FROM (VALUES
  ('一', '一', 'いち', 'uno'),
  ('一', '一月', 'いちがつ', 'enero'),
  ('一', '一緒', 'いっしょ', 'juntos'),
  ('七', '七', 'なな', 'siete'),
  ('七', '七月', 'しちがつ', 'julio'),
  ('七', '七夕', 'たなばた', 'Tanabata (festival de las estrellas)'),
  ('九', '九', 'きゅう', 'nueve'),
  ('九', '九月', 'くがつ', 'septiembre'),
  ('九', '九州', 'きゅうしゅう', 'Kyūshū (isla del sur de Japón)'),
  ('二', '二', 'に', 'dos'),
  ('二', '二月', 'にがつ', 'febrero'),
  ('二', '二人', 'ふたり', 'dos personas'),
  ('人', '人', 'ひと', 'persona'),
  ('人', '日本人', 'にほんじん', 'japonés (nacionalidad)'),
  ('人', '大人', 'おとな', 'adulto'),
  ('入', '入る', 'はいる', 'entrar'),
  ('入', '入口', 'いりぐち', 'entrada'),
  ('入', '記入', 'きにゅう', 'rellenar (un formulario)'),
  ('八', '八', 'はち', 'ocho'),
  ('八', '八月', 'はちがつ', 'agosto'),
  ('八', '八百屋', 'やおや', 'verdulería'),
  ('十', '十', 'じゅう', 'diez'),
  ('十', '十月', 'じゅうがつ', 'octubre'),
  ('十', '十字路', 'じゅうじろ', 'cruce / intersección'),
  ('万', '一万', 'いちまん', 'diez mil'),
  ('万', '万年筆', 'まんねんひつ', 'pluma estilográfica'),
  ('万', '万一', 'まんいち', 'por si acaso'),
  ('三', '三', 'さん', 'tres'),
  ('三', '三月', 'さんがつ', 'marzo'),
  ('三', '三角', 'さんかく', 'triángulo'),
  ('上', '上', 'うえ', 'arriba'),
  ('上', '上手', 'じょうず', 'hábil / bueno en algo'),
  ('上', '屋上', 'おくじょう', 'azotea'),
  ('下', '下', 'した', 'abajo'),
  ('下', '下手', 'へた', 'torpe / malo en algo'),
  ('下', '地下', 'ちか', 'subterráneo'),
  ('千', '千', 'せん', 'mil'),
  ('千', '千円', 'せんえん', 'mil yenes'),
  ('千', '千葉', 'ちば', 'prefectura de Chiba'),
  ('口', '口', 'くち', 'boca'),
  ('口', '入口', 'いりぐち', 'entrada'),
  ('口', '人口', 'じんこう', 'población'),
  ('土', '土', 'つち', 'tierra / suelo'),
  ('土', '土曜日', 'どようび', 'sábado'),
  ('土', '土地', 'とち', 'terreno'),
  ('大', '大きい', 'おおきい', 'grande'),
  ('大', '大学', 'だいがく', 'universidad'),
  ('大', '大切', 'たいせつ', 'importante'),
  ('女', '女', 'おんな', 'mujer'),
  ('女', '女性', 'じょせい', 'femenino / mujer'),
  ('女', '少女', 'しょうじょ', 'chica / muchacha'),
  ('子', '子供', 'こども', 'niño'),
  ('子', '女の子', 'おんなのこ', 'niña'),
  ('子', '男の子', 'おとこのこ', 'niño (varón)'),
  ('小', '小さい', 'ちいさい', 'pequeño'),
  ('小', '小学校', 'しょうがっこう', 'escuela primaria'),
  ('小', '小説', 'しょうせつ', 'novela'),
  ('山', '山', 'やま', 'montaña'),
  ('山', '富士山', 'ふじさん', 'monte Fuji'),
  ('山', '火山', 'かざん', 'volcán'),
  ('川', '川', 'かわ', 'río'),
  ('川', '小川', 'おがわ', 'arroyo'),
  ('川', '河川', 'かせん', 'ríos (formal)'),
  ('中', '中', 'なか', 'dentro / medio'),
  ('中', '中国', 'ちゅうごく', 'China'),
  ('中', '中学校', 'ちゅうがっこう', 'escuela secundaria'),
  ('五', '五', 'ご', 'cinco'),
  ('五', '五月', 'ごがつ', 'mayo'),
  ('五', '五十音', 'ごじゅうおん', 'silabario japonés (50 sonidos)'),
  ('今', '今', 'いま', 'ahora'),
  ('今', '今日', 'きょう', 'hoy'),
  ('今', '今月', 'こんげつ', 'este mes'),
  ('六', '六', 'ろく', 'seis'),
  ('六', '六月', 'ろくがつ', 'junio'),
  ('六', '六本木', 'ろっぽんぎ', 'Roppongi (barrio de Tokio)'),
  ('円', '円', 'えん', 'yen / círculo'),
  ('円', '千円', 'せんえん', 'mil yenes'),
  ('円', '円形', 'えんけい', 'circular / forma redonda'),
  ('分', '分', 'ふん', 'minuto'),
  ('分', '自分', 'じぶん', 'uno mismo'),
  ('分', '半分', 'はんぶん', 'mitad'),
  ('午', '午前', 'ごぜん', 'mañana / AM'),
  ('午', '午後', 'ごご', 'tarde / PM'),
  ('午', '正午', 'しょうご', 'mediodía'),
  ('友', '友達', 'ともだち', 'amigo'),
  ('友', '親友', 'しんゆう', 'mejor amigo'),
  ('友', '友情', 'ゆうじょう', 'amistad'),
  ('天', '天気', 'てんき', 'clima / tiempo'),
  ('天', '天国', 'てんごく', 'paraíso'),
  ('天', '天才', 'てんさい', 'genio'),
  ('少', '少ない', 'すくない', 'poco / escaso'),
  ('少', '少し', 'すこし', 'un poco'),
  ('少', '少年', 'しょうねん', 'niño / muchacho'),
  ('手', '手', 'て', 'mano'),
  ('手', '上手', 'じょうず', 'hábil / bueno en algo'),
  ('手', '手紙', 'てがみ', 'carta'),
  ('日', '日', 'ひ', 'día / sol'),
  ('日', '日本', 'にほん', 'Japón'),
  ('日', '毎日', 'まいにち', 'todos los días'),
  ('月', '月', 'つき', 'luna / mes'),
  ('月', '月曜日', 'げつようび', 'lunes'),
  ('月', '一月', 'いちがつ', 'enero'),
  ('木', '木', 'き', 'árbol'),
  ('木', '木曜日', 'もくようび', 'jueves'),
  ('木', '木材', 'もくざい', 'madera (material)'),
  ('水', '水', 'みず', 'agua'),
  ('水', '水曜日', 'すいようび', 'miércoles'),
  ('水', '水泳', 'すいえい', 'natación'),
  ('火', '火', 'ひ', 'fuego'),
  ('火', '火曜日', 'かようび', 'martes'),
  ('火', '花火', 'はなび', 'fuegos artificiales'),
  ('父', '父', 'ちち', 'padre (propio)'),
  ('父', 'お父さん', 'おとうさん', 'padre (ajeno)'),
  ('父', '父親', 'ちちおや', 'padre (formal)'),
  ('出', '出る', 'でる', 'salir'),
  ('出', '出口', 'でぐち', 'salida'),
  ('出', '出発', 'しゅっぱつ', 'partida / salida'),
  ('北', '北', 'きた', 'norte'),
  ('北', '東北', 'とうほく', 'región Tōhoku'),
  ('北', '北海道', 'ほっかいどう', 'Hokkaidō'),
  ('半', '半分', 'はんぶん', 'mitad'),
  ('半', '半年', 'はんとし', 'medio año'),
  ('半', '前半', 'ぜんはん', 'primera mitad'),
  ('古', '古い', 'ふるい', 'viejo / antiguo'),
  ('古', '中古', 'ちゅうこ', 'usado / segunda mano'),
  ('古', '古典', 'こてん', 'clásico (literatura)'),
  ('右', '右', 'みぎ', 'derecha'),
  ('右', '右手', 'みぎて', 'mano derecha'),
  ('右', '右側', 'みぎがわ', 'lado derecho'),
  ('四', '四', 'よん', 'cuatro'),
  ('四', '四月', 'しがつ', 'abril'),
  ('四', '四季', 'しき', 'las cuatro estaciones'),
  ('外', '外', 'そと', 'afuera'),
  ('外', '外国', 'がいこく', 'extranjero (país)'),
  ('外', '外食', 'がいしょく', 'comer fuera'),
  ('左', '左', 'ひだり', 'izquierda'),
  ('左', '左手', 'ひだりて', 'mano izquierda'),
  ('左', '左側', 'ひだりがわ', 'lado izquierdo'),
  ('未', '未来', 'みらい', 'futuro'),
  ('未', '未定', 'みてい', 'no decidido / por definir'),
  ('未', '未成年', 'みせいねん', 'menor de edad'),
  ('本', '本', 'ほん', 'libro'),
  ('本', '日本', 'にほん', 'Japón'),
  ('本', '本当', 'ほんとう', 'verdad'),
  ('母', '母', 'はは', 'madre (propia)'),
  ('母', 'お母さん', 'おかあさん', 'madre (ajena)'),
  ('母', '母国', 'ぼこく', 'patria / país natal'),
  ('生', '生きる', 'いきる', 'vivir'),
  ('生', '学生', 'がくせい', 'estudiante'),
  ('生', '先生', 'せんせい', 'profesor'),
  ('白', '白い', 'しろい', 'blanco'),
  ('白', '白鳥', 'はくちょう', 'cisne'),
  ('白', '面白い', 'おもしろい', 'interesante / divertido'),
  ('目', '目', 'め', 'ojo'),
  ('目', '目的', 'もくてき', 'objetivo'),
  ('目', '目薬', 'めぐすり', 'colirio / gotas oculares'),
  ('立', '立つ', 'たつ', 'pararse / ponerse de pie'),
  ('立', '国立', 'こくりつ', 'nacional (institución pública)'),
  ('立', '立派', 'りっぱ', 'espléndido / imponente'),
  ('休', '休む', 'やすむ', 'descansar'),
  ('休', '休日', 'きゅうじつ', 'día festivo / feriado'),
  ('休', '夏休み', 'なつやすみ', 'vacaciones de verano'),
  ('会', '会う', 'あう', 'encontrarse / reunirse'),
  ('会', '会社', 'かいしゃ', 'empresa'),
  ('会', '会議', 'かいぎ', 'reunión / junta'),
  ('先', '先', 'さき', 'antes / adelante'),
  ('先', '先生', 'せんせい', 'profesor'),
  ('先', '先週', 'せんしゅう', 'semana pasada'),
  ('名', '名前', 'なまえ', 'nombre'),
  ('名', '有名', 'ゆうめい', 'famoso'),
  ('名', '名刺', 'めいし', 'tarjeta de presentación'),
  ('多', '多い', 'おおい', 'mucho / muchos'),
  ('多', '多分', 'たぶん', 'probablemente / quizás'),
  ('多', '多数', 'たすう', 'mayoría / gran número'),
  ('安', '安い', 'やすい', 'barato'),
  ('安', '安全', 'あんぜん', 'seguro / seguridad'),
  ('安', '安心', 'あんしん', 'tranquilidad / alivio'),
  ('年', '年', 'とし', 'año / edad'),
  ('年', '今年', 'ことし', 'este año'),
  ('年', '来年', 'らいねん', 'año próximo'),
  ('毎', '毎日', 'まいにち', 'todos los días'),
  ('毎', '毎週', 'まいしゅう', 'todas las semanas'),
  ('毎', '毎年', 'まいとし', 'todos los años'),
  ('気', '元気', 'げんき', 'saludable / con energía'),
  ('気', '天気', 'てんき', 'clima / tiempo'),
  ('気', '気持ち', 'きもち', 'sentimiento / sensación'),
  ('百', '百', 'ひゃく', 'cien'),
  ('百', '百年', 'ひゃくねん', 'cien años'),
  ('百', '百科事典', 'ひゃっかじてん', 'enciclopedia'),
  ('耳', '耳', 'みみ', 'oreja / oído'),
  ('耳', '耳鼻科', 'じびか', 'otorrinolaringología'),
  ('耳', '空耳', 'そらみみ', 'oír algo que no se dijo'),
  ('行', '行く', 'いく', 'ir'),
  ('行', '銀行', 'ぎんこう', 'banco'),
  ('行', '旅行', 'りょこう', 'viaje'),
  ('西', '西', 'にし', 'oeste'),
  ('西', '西洋', 'せいよう', 'Occidente'),
  ('西', '関西', 'かんさい', 'región Kansai'),
  ('何', '何', 'なに', 'qué'),
  ('何', '何時', 'なんじ', 'qué hora'),
  ('何', '何回', 'なんかい', 'cuántas veces'),
  ('男', '男', 'おとこ', 'hombre'),
  ('男', '男性', 'だんせい', 'masculino / hombre'),
  ('男', '長男', 'ちょうなん', 'hijo mayor'),
  ('社', '会社', 'かいしゃ', 'empresa'),
  ('社', '神社', 'じんじゃ', 'santuario shintō'),
  ('社', '社長', 'しゃちょう', 'presidente de empresa'),
  ('花', '花', 'はな', 'flor'),
  ('花', '花見', 'はなみ', 'contemplación de las flores'),
  ('花', '花火', 'はなび', 'fuegos artificiales'),
  ('見', '見る', 'みる', 'ver / mirar'),
  ('見', '花見', 'はなみ', 'contemplación de las flores'),
  ('見', '意見', 'いけん', 'opinión'),
  ('言', '言う', 'いう', 'decir'),
  ('言', '言葉', 'ことば', 'palabra / idioma'),
  ('言', '方言', 'ほうげん', 'dialecto'),
  ('足', '足', 'あし', 'pie / pierna'),
  ('足', '足りる', 'たりる', 'ser suficiente'),
  ('足', '遠足', 'えんそく', 'excursión'),
  ('車', '車', 'くるま', 'auto / vehículo'),
  ('車', '電車', 'でんしゃ', 'tren'),
  ('車', '自転車', 'じてんしゃ', 'bicicleta'),
  ('国', '国', 'くに', 'país'),
  ('国', '外国', 'がいこく', 'extranjero (país)'),
  ('国', '中国', 'ちゅうごく', 'China'),
  ('学', '学ぶ', 'まなぶ', 'aprender'),
  ('学', '学校', 'がっこう', 'escuela'),
  ('学', '大学', 'だいがく', 'universidad'),
  ('店', '店', 'みせ', 'tienda'),
  ('店', '店員', 'てんいん', 'dependiente / empleado'),
  ('店', '書店', 'しょてん', 'librería'),
  ('東', '東', 'ひがし', 'este (punto cardinal)'),
  ('東', '東京', 'とうきょう', 'Tokio'),
  ('東', '東洋', 'とうよう', 'Oriente'),
  ('空', '空', 'そら', 'cielo'),
  ('空', '空港', 'くうこう', 'aeropuerto'),
  ('空', '青空', 'あおぞら', 'cielo azul'),
  ('金', 'お金', 'おかね', 'dinero'),
  ('金', '金曜日', 'きんようび', 'viernes'),
  ('金', '現金', 'げんきん', 'dinero en efectivo'),
  ('長', '長い', 'ながい', 'largo'),
  ('長', '社長', 'しゃちょう', 'presidente de empresa'),
  ('長', '校長', 'こうちょう', 'director de escuela'),
  ('雨', '雨', 'あめ', 'lluvia'),
  ('雨', '大雨', 'おおあめ', 'lluvia fuerte'),
  ('雨', '梅雨', 'つゆ', 'temporada de lluvias'),
  ('前', '前', 'まえ', 'antes / delante'),
  ('前', '名前', 'なまえ', 'nombre'),
  ('前', '午前', 'ごぜん', 'mañana / AM'),
  ('南', '南', 'みなみ', 'sur'),
  ('南', '南極', 'なんきょく', 'Antártida'),
  ('南', '南米', 'なんべい', 'Sudamérica'),
  ('後', '後ろ', 'うしろ', 'atrás'),
  ('後', '午後', 'ごご', 'tarde / PM'),
  ('後', '最後', 'さいご', 'el último / final'),
  ('食', '食べる', 'たべる', 'comer'),
  ('食', '食事', 'しょくじ', 'comida'),
  ('食', '朝食', 'ちょうしょく', 'desayuno'),
  ('時', '時間', 'じかん', 'tiempo / hora'),
  ('時', '時計', 'とけい', 'reloj'),
  ('時', '何時', 'なんじ', 'qué hora'),
  ('書', '書く', 'かく', 'escribir'),
  ('書', '図書館', 'としょかん', 'biblioteca'),
  ('書', '辞書', 'じしょ', 'diccionario'),
  ('校', '学校', 'がっこう', 'escuela'),
  ('校', '校長', 'こうちょう', 'director de escuela'),
  ('校', '高校', 'こうこう', 'secundaria alta'),
  ('高', '高い', 'たかい', 'alto / caro'),
  ('高', '高校', 'こうこう', 'secundaria alta'),
  ('高', '最高', 'さいこう', 'el mejor / máximo'),
  ('週', '週', 'しゅう', 'semana'),
  ('週', '今週', 'こんしゅう', 'esta semana'),
  ('週', '週末', 'しゅうまつ', 'fin de semana'),
  ('魚', '魚', 'さかな', 'pescado / pez'),
  ('魚', '金魚', 'きんぎょ', 'pez dorado / carassius'),
  ('魚', '人魚', 'にんぎょ', 'sirena'),
  ('買', '買う', 'かう', 'comprar'),
  ('買', '買い物', 'かいもの', 'compras'),
  ('買', '売買', 'ばいばい', 'compraventa'),
  ('道', '道', 'みち', 'camino'),
  ('道', '道路', 'どうろ', 'carretera / vía'),
  ('道', '北海道', 'ほっかいどう', 'Hokkaidō'),
  ('間', '間', 'あいだ', 'entre / intervalo'),
  ('間', '時間', 'じかん', 'tiempo / hora'),
  ('間', '人間', 'にんげん', 'ser humano'),
  ('飲', '飲む', 'のむ', 'beber'),
  ('飲', '飲み物', 'のみもの', 'bebida'),
  ('飲', '飲料', 'いんりょう', 'bebida (formal)'),
  ('新', '新しい', 'あたらしい', 'nuevo'),
  ('新', '新聞', 'しんぶん', 'periódico'),
  ('新', '新幹線', 'しんかんせん', 'tren bala'),
  ('話', '話す', 'はなす', 'hablar'),
  ('話', '電話', 'でんわ', 'teléfono'),
  ('話', '会話', 'かいわ', 'conversación'),
  ('電', '電気', 'でんき', 'electricidad / luz'),
  ('電', '電車', 'でんしゃ', 'tren'),
  ('電', '電話', 'でんわ', 'teléfono'),
  ('聞', '聞く', 'きく', 'escuchar / preguntar'),
  ('聞', '新聞', 'しんぶん', 'periódico'),
  ('聞', '聞き手', 'ききて', 'oyente / interlocutor'),
  ('語', '日本語', 'にほんご', 'idioma japonés'),
  ('語', '英語', 'えいご', 'idioma inglés'),
  ('語', '単語', 'たんご', 'vocablo / palabra suelta'),
  ('読', '読む', 'よむ', 'leer'),
  ('読', '読書', 'どくしょ', 'lectura'),
  ('読', '音読', 'おんどく', 'lectura en voz alta'),
  ('駅', '駅', 'えき', 'estación'),
  ('駅', '駅員', 'えきいん', 'personal de estación'),
  ('駅', '東京駅', 'とうきょうえき', 'estación de Tokio')
) AS v(caracter, palabra, furigana, traduccion)
JOIN kanji k ON k.caracter = v.caracter;
