//layout RAIZ-- persiste
import type { Metadata } from "next";
import { Oxanium } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout-components/Navbar";
import Footer from "@/components/layout-components/Footer";
import DigitalRain from "@/components/effects/DigitalRain";

const oxanium = Oxanium({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-oxanium",
});

export const metadata: Metadata = {
  title: "bizaphy lab",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${oxanium.className} antialiased min-h-screen flex flex-col`}
      >
        <DigitalRain />
        <Navbar />
        <main className="flex-1 relative z-10">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
