-- ============================================================
-- SEED: kanji N4 (185 caracteres)
-- Fuente: imagen "N4 Kanji [about 180]" + imagen "N4 Kanji [not
-- including N5]" organizada por categorias, para subir a Neon
-- ============================================================

-- Mismo criterio que los seeds anteriores: no se toca la nulabilidad
-- de tu schema.ts (numero_trazos NOT NULL se respeta, se completa con
-- datos reales). significado / anio_escolar_japon usan las columnas
-- que ya agregaste tu.
--
-- numero_trazos, onyomi, kunyomi: dataset publico (KANJIDIC2 + WaniKani,
-- via github.com/davidluzgouveia/kanji-data). Notacion tal cual KANJIDIC:
-- el punto (.) marca donde empieza la okurigana (ej. "はや.い" = 早い),
-- el guion (-) marca lecturas de prefijo/sufijo, "、" separa lecturas
-- multiples. Los kanji sin kunyomi propio quedan en NULL (normal).
--
-- ACTUALIZACION vs la version anterior de este seed:
--  * 6 kanji nuevos (apareicen en la 2da imagen, no en la 1ra):
--    研, 究, 建, 有, 度, 質
--  * anio_escolar_japon corregido de 3 a 4 para 11 kanji, segun la
--    2da imagen: 試, 験, 説, 産, 飯, 無, 以, 英, 民, 借, 便
--  * url_imagen_mnemotecnica poblada con archivos .webp locales de
--    /public/images/projects/all-about-kanjis/mnemotecnias/n4/
--    Los que no tienen imagen local quedan en NULL.
--
-- NOTA: 未 sigue excluido -- ya esta cargado como n5 en el otro seed
-- (caracter es UNIQUE en tu tabla). Avisame si prefieres que pase a n4.
--
-- ON CONFLICT (caracter) DO UPDATE -> se puede correr mas de una vez
-- sin duplicar filas, y sirve tambien para aplicar esta actualizacion
-- si ya habias corrido la version anterior del seed.
-- --------------------------------------------------------------

INSERT INTO kanji (caracter, nivel, anio_escolar_japon, significado, onyomi, kunyomi, numero_trazos, url_orden_trazos, frase_mnemotecnica, url_imagen_mnemotecnica)
VALUES
  ('正', 'n4'::nivel_jlpt, 1, 'correcto / justo', 'せい、しょう', 'ただ.しい、ただ.す、まさ、まさ.に', 5, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/correct.webp'),
  ('早', 'n4'::nivel_jlpt, 1, 'temprano', 'そう、さっ', 'はや.い、はや、はや-、はや.まる、はや.める、さ-', 6, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/early.webp'),
  ('赤', 'n4'::nivel_jlpt, 1, 'rojo', 'せき、しゃく', 'あか、あか-、あか.い、あか.らむ、あか.らめる', 7, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/red.webp'),
  ('青', 'n4'::nivel_jlpt, 1, 'azul', 'せい、しょう', 'あお、あお-、あお.い', 8, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/blue.webp'),
  ('犬', 'n4'::nivel_jlpt, 1, 'perro', 'けん', 'いぬ、いぬ-', 4, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/dog.webp'),
  ('田', 'n4'::nivel_jlpt, 1, 'campo de arroz', 'でん', 'た', 5, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/rice%20paddy.webp'),
  ('町', 'n4'::nivel_jlpt, 1, 'pueblo / ciudad', 'ちょう', 'まち', 7, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/town.webp'),
  ('夕', 'n4'::nivel_jlpt, 1, 'atardecer', 'せき', 'ゆう', 3, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/evening.webp'),
  ('文', 'n4'::nivel_jlpt, 1, 'texto / oración', 'ぶん、もん', 'ふみ、あや', 4, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/sentence.webp'),
  ('字', 'n4'::nivel_jlpt, 1, 'letra / carácter', 'じ', 'あざ、あざな、-な', 6, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/letter,character.webp'),
  ('音', 'n4'::nivel_jlpt, 1, 'sonido', 'おん、いん、-のん', 'おと、ね', 9, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/sound.webp'),
  ('力', 'n4'::nivel_jlpt, 1, 'fuerza', 'りょく、りき、りい', 'ちから', 2, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/power.webp'),
  ('林', 'n4'::nivel_jlpt, 1, 'bosque pequeño', 'りん', 'はやし', 8, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/bush.webp'),
  ('森', 'n4'::nivel_jlpt, 1, 'bosque', 'しん', 'もり', 12, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/forest.webp'),
  ('村', 'n4'::nivel_jlpt, 1, 'pueblo / aldea', 'そん', 'むら', 7, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/village.webp'),
  ('強', 'n4'::nivel_jlpt, 2, 'fuerte', 'きょう、ごう', 'つよ.い、つよ.まる、つよ.める、し.いる、こわ.い', 11, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/tsuyoi.webp'),
  ('弱', 'n4'::nivel_jlpt, 2, 'débil', 'じゃく', 'よわ.い、よわ.る、よわ.まる、よわ.める', 10, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/yowai.webp'),
  ('楽', 'n4'::nivel_jlpt, 2, 'fácil / música / disfrutar', 'がく、らく、ごう', 'たの.しい、たの.しむ、この.む', 13, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/fun.webp'),
  ('春', 'n4'::nivel_jlpt, 2, 'primavera', 'しゅん', 'はる', 9, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/spring.webp'),
  ('夏', 'n4'::nivel_jlpt, 2, 'verano', 'か、が、げ', 'なつ', 10, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/summer.webp'),
  ('秋', 'n4'::nivel_jlpt, 2, 'otoño', 'しゅう', 'あき、とき', 9, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/autumn.webp'),
  ('冬', 'n4'::nivel_jlpt, 2, 'invierno', 'とう', 'ふゆ', 5, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/winter.webp'),
  ('色', 'n4'::nivel_jlpt, 2, 'color', 'しょく、しき', 'いろ', 6, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/colour.webp'),
  ('黒', 'n4'::nivel_jlpt, 2, 'negro', 'こく', 'くろ、くろ.ずむ、くろ.い', 11, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/black.webp'),
  ('茶', 'n4'::nivel_jlpt, 2, 'té', 'ちゃ、さ', NULL, 9, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/tea.webp'),
  ('兄', 'n4'::nivel_jlpt, 2, 'hermano mayor', 'けい、きょう', 'あに', 5, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/older%20brother.webp'),
  ('弟', 'n4'::nivel_jlpt, 2, 'hermano menor', 'てい、だい、で', 'おとうと', 7, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/younger%20brother.webp'),
  ('姉', 'n4'::nivel_jlpt, 2, 'hermana mayor', 'し', 'あね、はは', 8, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/older%20sister.webp'),
  ('妹', 'n4'::nivel_jlpt, 2, 'hermana menor', 'まい', 'いもうと', 8, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/younger%20sister.webp'),
  ('牛', 'n4'::nivel_jlpt, 2, 'vaca / res', 'ぎゅう', 'うし', 4, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/cow.webp'),
  ('鳥', 'n4'::nivel_jlpt, 2, 'pájaro', 'ちょう', 'とり', 11, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/bird.webp'),
  ('地', 'n4'::nivel_jlpt, 2, 'tierra / suelo', 'ち、じ', NULL, 6, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/land,%20ground.webp'),
  ('京', 'n4'::nivel_jlpt, 2, 'capital', 'きょう、けい、きん', 'みやこ', 8, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/capital.webp'),
  ('門', 'n4'::nivel_jlpt, 2, 'puerta', 'もん', 'かど、と', 8, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/gate.webp'),
  ('晴', 'n4'::nivel_jlpt, 2, 'despejado (clima)', 'せい', 'は.れる、は.れ、は.れ-、-ば.れ、は.らす', 12, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/sunny.webp'),
  ('家', 'n4'::nivel_jlpt, 2, 'casa', 'か、け', 'いえ、や、うち', 10, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/house.webp'),
  ('方', 'n4'::nivel_jlpt, 2, 'dirección / persona (honorífico)', 'ほう', 'かた、-かた、-がた', 4, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/direction.webp'),
  ('光', 'n4'::nivel_jlpt, 2, 'luz', 'こう', 'ひか.る、ひかり', 6, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/light.webp'),
  ('海', 'n4'::nivel_jlpt, 2, 'mar', 'かい', 'うみ', 9, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/ocean.webp'),
  ('台', 'n4'::nivel_jlpt, 2, 'base / plataforma', 'だい、たい', 'うてな、われ、つかさ', 5, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/stand,%20stage.webp'),
  ('室', 'n4'::nivel_jlpt, 2, 'habitación', 'しつ', 'むろ', 9, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/room.webp'),
  ('朝', 'n4'::nivel_jlpt, 2, 'mañana', 'ちょう', 'あさ', 12, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/morning.webp'),
  ('昼', 'n4'::nivel_jlpt, 2, 'mediodía', 'ちゅう', 'ひる', 9, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/daytime.webp'),
  ('夜', 'n4'::nivel_jlpt, 2, 'noche', 'や', 'よ、よる', 8, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/night.webp'),
  ('回', 'n4'::nivel_jlpt, 2, 'vez / vuelta', 'かい、え', 'まわ.る、-まわ.る、-まわ.り、まわ.す、-まわ.す、まわ.し-、-まわ.し、もとお.る、か.える', 6, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/go%20around.webp'),
  ('池', 'n4'::nivel_jlpt, 2, 'estanque', 'ち', 'いけ', 6, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/pond.webp'),
  ('作', 'n4'::nivel_jlpt, 2, 'hacer / crear', 'さく、さ', 'つく.る、つく.り、-づく.り', 7, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/to%20make.webp'),
  ('走', 'n4'::nivel_jlpt, 2, 'correr', 'そう', 'はし.る', 7, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/to%20run.webp'),
  ('首', 'n4'::nivel_jlpt, 2, 'cuello', 'しゅ', 'くび', 9, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/neck.webp'),
  ('売', 'n4'::nivel_jlpt, 2, 'vender', 'ばい', 'う.る、う.れる', 7, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/to%20sell.webp'),
  ('止', 'n4'::nivel_jlpt, 2, 'detener', 'し', 'と.まる、-ど.まり、と.める、-と.める、-ど.め、とど.める、とど.め、とど.まる、や.める、や.む、-や.む、よ.す、-さ.す、-さ.し', 4, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/to%20stop.webp'),
  ('親', 'n4'::nivel_jlpt, 2, 'padre o madre / cercano', 'しん', 'おや、おや-、した.しい、した.しむ', 16, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/parent.webp'),
  ('市', 'n4'::nivel_jlpt, 2, 'ciudad / mercado', 'し', 'いち', 5, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/city,%20market.webp'),
  ('引', 'n4'::nivel_jlpt, 2, 'tirar / jalar', 'いん', 'ひ.く、ひ.き、ひ.き-、-び.き、ひ.ける', 4, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/to%20draw,%20pull.webp'),
  ('太', 'n4'::nivel_jlpt, 2, 'grueso / gordo', 'たい、た', 'ふと.い、ふと.る', 4, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/thick,%20wide.webp'),
  ('合', 'n4'::nivel_jlpt, 2, 'unir / coincidir', 'ごう、がっ、かっ', 'あ.う、-あ.う、あ.い、あい-、-あ.い、-あい、あ.わす、あ.わせる、-あ.わせる', 6, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/to%20fit.webp'),
  ('遠', 'n4'::nivel_jlpt, 2, 'lejos', 'えん、おん', 'とお.い', 13, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/far.webp'),
  ('近', 'n4'::nivel_jlpt, 2, 'cerca', 'きん、こん', 'ちか.い', 7, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/close,%20near.webp'),
  ('広', 'n4'::nivel_jlpt, 2, 'amplio', 'こう', 'ひろ.い、ひろ.まる、ひろ.める、ひろ.がる、ひろ.げる', 5, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/spacious,%20wide.webp'),
  ('明', 'n4'::nivel_jlpt, 2, 'claro / brillante', 'めい、みょう、みん', 'あ.かり、あか.るい、あか.るむ、あか.らむ、あき.らか、あ.ける、-あ.け、あ.く、あ.くる、あ.かす', 8, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/bright.webp'),
  ('切', 'n4'::nivel_jlpt, 2, 'cortar', 'せつ、さい', 'き.る、-き.る、き.り、-き.り、-ぎ.り、き.れる、-き.れる、き.れ、-き.れ、-ぎ.れ', 4, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/to%20cut.webp'),
  ('心', 'n4'::nivel_jlpt, 2, 'corazón / mente', 'しん', 'こころ、-ごころ', 4, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/heart.webp'),
  ('体', 'n4'::nivel_jlpt, 2, 'cuerpo', 'たい、てい', 'からだ、かたち', 7, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/body.webp'),
  ('同', 'n4'::nivel_jlpt, 2, 'igual / mismo', 'どう', 'おな.じ', 6, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/same.webp'),
  ('自', 'n4'::nivel_jlpt, 2, 'uno mismo', 'じ、し', 'みずか.ら、おの.ずから、おの.ずと', 6, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/self.webp'),
  ('肉', 'n4'::nivel_jlpt, 2, 'carne', 'にく', 'しし', 6, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/meat.webp'),
  ('工', 'n4'::nivel_jlpt, 2, 'trabajo / construcción', 'こう、く、ぐ', NULL, 3, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/craft,%20labour.webp'),
  ('公', 'n4'::nivel_jlpt, 2, 'público', 'こう、く', 'おおやけ', 4, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/public.webp'),
  ('元', 'n4'::nivel_jlpt, 2, 'origen', 'げん、がん', 'もと', 4, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/energetic.webp'),
  ('風', 'n4'::nivel_jlpt, 2, 'viento', 'ふう、ふ', 'かぜ、かざ-、-かぜ', 9, NULL, NULL, NULL),
  ('声', 'n4'::nivel_jlpt, 2, 'voz', 'せい、しょう', 'こえ、こわ-', 7, NULL, NULL, NULL),
  ('曜', 'n4'::nivel_jlpt, 2, 'día de la semana', 'よう', NULL, 18, NULL, NULL, NULL),
  ('思', 'n4'::nivel_jlpt, 2, 'pensar', 'し', 'おも.う、おもえら.く、おぼ.す', 9, NULL, NULL, NULL),
  ('知', 'n4'::nivel_jlpt, 2, 'saber / conocer', 'ち', 'し.る、し.らせる', 8, NULL, NULL, NULL),
  ('通', 'n4'::nivel_jlpt, 2, 'pasar / comunicar', 'つう、つ', 'とお.る、とお.り、-とお.り、-どお.り、とお.す、とお.し、-どお.し、かよ.う', 10, NULL, NULL, NULL),
  ('顔', 'n4'::nivel_jlpt, 2, 'cara', 'がん', 'かお', 18, NULL, NULL, NULL),
  ('頭', 'n4'::nivel_jlpt, 2, 'cabeza', 'とう、ず、と', 'あたま、かしら、-がしら、かぶり', 16, NULL, NULL, NULL),
  ('歩', 'n4'::nivel_jlpt, 2, 'caminar', 'ほ、ぶ、ふ', 'ある.く、あゆ.む', 8, NULL, NULL, NULL),
  ('歌', 'n4'::nivel_jlpt, 2, 'canción / cantar', 'か', 'うた、うた.う', 14, NULL, NULL, NULL),
  ('図', 'n4'::nivel_jlpt, 2, 'diagrama / dibujo', 'ず、と', 'え、はか.る', 7, NULL, NULL, NULL),
  ('画', 'n4'::nivel_jlpt, 2, 'dibujo / pintura', 'が、かく、え、かい', 'えが.く、かく.する、かぎ.る、はかりごと、はか.る', 8, NULL, NULL, NULL),
  ('計', 'n4'::nivel_jlpt, 2, 'medir / plan', 'けい', 'はか.る、はか.らう', 9, NULL, NULL, NULL),
  ('場', 'n4'::nivel_jlpt, 2, 'lugar', 'じょう、ちょう', 'ば', 12, NULL, NULL, NULL),
  ('考', 'n4'::nivel_jlpt, 2, 'pensar', 'こう', 'かんが.える、かんが.え', 6, NULL, NULL, NULL),
  ('野', 'n4'::nivel_jlpt, 2, 'campo / llanura', 'や、しょ', 'の、の-', 11, NULL, NULL, NULL),
  ('理', 'n4'::nivel_jlpt, 2, 'razón / lógica', 'り', 'ことわり', 11, NULL, NULL, NULL),
  ('答', 'n4'::nivel_jlpt, 2, 'responder', 'とう', 'こた.える、こた.え', 12, NULL, NULL, NULL),
  ('教', 'n4'::nivel_jlpt, 2, 'enseñar', 'きょう', 'おし.える、おそ.わる', 11, NULL, NULL, NULL),
  ('帰', 'n4'::nivel_jlpt, 2, 'regresar', 'き', 'かえ.る、かえ.す、おく.る、とつ.ぐ', 10, NULL, NULL, NULL),
  ('紙', 'n4'::nivel_jlpt, 2, 'papel', 'し', 'かみ', 10, NULL, NULL, NULL),
  ('用', 'n4'::nivel_jlpt, 2, 'uso / usar', 'よう', 'もち.いる', 5, NULL, NULL, NULL),
  ('薬', 'n4'::nivel_jlpt, 3, 'medicina', 'やく', 'くすり', 16, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/medicine.webp'),
  ('重', 'n4'::nivel_jlpt, 3, 'pesado / importante', 'じゅう、ちょう', 'え、おも.い、おも.り、おも.なう、かさ.ねる、かさ.なる、おも', 9, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/heavy.webp'),
  ('者', 'n4'::nivel_jlpt, 3, 'persona', 'しゃ', 'もの', 8, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/those%20who%20(mono).webp'),
  ('待', 'n4'::nivel_jlpt, 3, 'esperar', 'たい', 'ま.つ、-ま.ち', 9, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/to%20wait.webp'),
  ('持', 'n4'::nivel_jlpt, 3, 'sostener / tener', 'じ', 'も.つ、-も.ち、も.てる', 9, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/to%20have,%20hold.webp'),
  ('動', 'n4'::nivel_jlpt, 3, 'moverse', 'どう', 'うご.く、うご.かす', 11, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/to%20move.webp'),
  ('始', 'n4'::nivel_jlpt, 3, 'comenzar', 'し', 'はじ.める、-はじ.める、はじ.まる', 8, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/to%20start.webp'),
  ('暑', 'n4'::nivel_jlpt, 3, 'caluroso', 'しょ', 'あつ.い', 12, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/hot%20weather%20(atsui).webp'),
  ('寒', 'n4'::nivel_jlpt, 3, 'frío', 'かん', 'さむ.い', 12, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/cold%20weather%20(samui).webp'),
  ('味', 'n4'::nivel_jlpt, 3, 'sabor', 'み', 'あじ、あじ.わう', 8, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/taste.webp'),
  ('開', 'n4'::nivel_jlpt, 3, 'abrir', 'かい', 'ひら.く、ひら.き、-びら.き、ひら.ける、あ.く、あ.ける', 12, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/to%20open.webp'),
  ('問', 'n4'::nivel_jlpt, 3, 'pregunta', 'もん', 'と.う、と.い、とん', 11, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/question.webp'),
  ('運', 'n4'::nivel_jlpt, 3, 'transportar / suerte', 'うん', 'はこ.ぶ', 12, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/to%20carry.webp'),
  ('転', 'n4'::nivel_jlpt, 3, 'girar / rodar', 'てん', 'ころ.がる、ころ.げる、ころ.がす、ころ.ぶ、まろ.ぶ、うたた、うつ.る、くる.めく', 11, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/to%20fall%20over.webp'),
  ('品', 'n4'::nivel_jlpt, 3, 'producto / artículo', 'ひん、ほん', 'しな', 9, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/goods,%20products.webp'),
  ('屋', 'n4'::nivel_jlpt, 3, 'tienda / techo', 'おく', 'や', 9, NULL, NULL, NULL),
  ('急', 'n4'::nivel_jlpt, 3, 'urgente / rápido', 'きゅう', 'いそ.ぐ、いそ.ぎ、せ.く', 9, NULL, NULL, NULL),
  ('意', 'n4'::nivel_jlpt, 3, 'intención / significado', 'い', NULL, 13, NULL, NULL, NULL),
  ('悪', 'n4'::nivel_jlpt, 3, 'malo', 'あく、お', 'わる.い、わる-、あ.し、にく.い、-にく.い、ああ、いずくに、いずくんぞ、にく.む', 11, NULL, NULL, NULL),
  ('暗', 'n4'::nivel_jlpt, 3, 'oscuro', 'あん', 'くら.い、くら.む、くれ.る', 13, NULL, NULL, NULL),
  ('世', 'n4'::nivel_jlpt, 3, 'mundo / era', 'せい、せ、そう', 'よ', 5, NULL, NULL, NULL),
  ('界', 'n4'::nivel_jlpt, 3, 'límite / mundo', 'かい', NULL, 9, NULL, NULL, NULL),
  ('住', 'n4'::nivel_jlpt, 3, 'vivir / residir', 'じゅう、ぢゅう、ちゅう', 'す.む、す.まう、-ず.まい', 7, NULL, NULL, NULL),
  ('洋', 'n4'::nivel_jlpt, 3, 'océano / occidental', 'よう', NULL, 9, NULL, NULL, NULL),
  ('注', 'n4'::nivel_jlpt, 3, 'verter / prestar atención', 'ちゅう', 'そそ.ぐ、さ.す、つ.ぐ', 8, NULL, NULL, NULL),
  ('死', 'n4'::nivel_jlpt, 3, 'muerte', 'し', 'し.ぬ、し.に-', 6, NULL, NULL, NULL),
  ('漢', 'n4'::nivel_jlpt, 3, 'kanji / chino (Han)', 'かん', NULL, 13, NULL, NULL, NULL),
  ('主', 'n4'::nivel_jlpt, 3, 'principal / dueño', 'しゅ、す、しゅう', 'ぬし、おも、あるじ', 5, NULL, NULL, NULL),
  ('送', 'n4'::nivel_jlpt, 3, 'enviar', 'そう', 'おく.る', 9, NULL, NULL, NULL),
  ('進', 'n4'::nivel_jlpt, 3, 'avanzar', 'しん', 'すす.む、すす.める', 11, NULL, NULL, NULL),
  ('去', 'n4'::nivel_jlpt, 3, 'irse / pasado', 'きょ、こ', 'さ.る、-さ.る', 5, NULL, NULL, NULL),
  ('集', 'n4'::nivel_jlpt, 3, 'reunir / colección', 'しゅう', 'あつ.まる、あつ.める、つど.う', 12, NULL, NULL, NULL),
  ('起', 'n4'::nivel_jlpt, 3, 'levantarse / ocurrir', 'き', 'お.きる、お.こる、お.こす、おこ.す、た.つ', 10, NULL, NULL, NULL),
  ('勉', 'n4'::nivel_jlpt, 3, 'esforzarse (勉強 = estudiar)', 'べん', 'つと.める', 10, NULL, NULL, NULL),
  ('写', 'n4'::nivel_jlpt, 3, 'copiar / fotografiar', 'しゃ、じゃ', 'うつ.す、うつ.る、うつ-、うつ.し', 5, NULL, NULL, NULL),
  ('真', 'n4'::nivel_jlpt, 3, 'verdad / real', 'しん', 'ま、ま-、まこと', 10, NULL, NULL, NULL),
  ('仕', 'n4'::nivel_jlpt, 3, 'servir (trabajo)', 'し、じ', 'つか.える', 5, NULL, NULL, NULL),
  ('事', 'n4'::nivel_jlpt, 3, 'asunto / cosa', 'じ、ず', 'こと、つか.う、つか.える', 8, NULL, NULL, NULL),
  ('館', 'n4'::nivel_jlpt, 3, 'edificio / salón', 'かん', 'やかた、たて', 16, NULL, NULL, NULL),
  ('服', 'n4'::nivel_jlpt, 3, 'ropa', 'ふく', NULL, 8, NULL, NULL, NULL),
  ('院', 'n4'::nivel_jlpt, 3, 'institución', 'いん', NULL, 10, NULL, NULL, NULL),
  ('病', 'n4'::nivel_jlpt, 3, 'enfermedad', 'びょう、へい', 'や.む、-や.み、やまい', 10, NULL, NULL, NULL),
  ('医', 'n4'::nivel_jlpt, 3, 'medicina / médico', 'い', 'い.やす、い.する、くすし', 7, NULL, NULL, NULL),
  ('使', 'n4'::nivel_jlpt, 3, 'usar / enviar a alguien', 'し', 'つか.う、つか.い、-つか.い、-づか.い', 8, NULL, NULL, NULL),
  ('旅', 'n4'::nivel_jlpt, 3, 'viaje', 'りょ', 'たび', 10, NULL, NULL, NULL),
  ('族', 'n4'::nivel_jlpt, 3, 'familia / clan', 'ぞく', NULL, 11, NULL, NULL, NULL),
  ('所', 'n4'::nivel_jlpt, 3, 'lugar', 'しょ', 'ところ、-ところ、どころ、とこ', 8, NULL, NULL, NULL),
  ('乗', 'n4'::nivel_jlpt, 3, 'subir / montar', 'じょう、しょう', 'の.る、-の.り、の.せる', 9, NULL, NULL, NULL),
  ('物', 'n4'::nivel_jlpt, 3, 'objeto / cosa', 'ぶつ、もつ', 'もの、もの-', 8, NULL, NULL, NULL),
  ('短', 'n4'::nivel_jlpt, 3, 'corto', 'たん', 'みじか.い', 12, NULL, NULL, NULL),
  ('員', 'n4'::nivel_jlpt, 3, 'miembro', 'いん', NULL, 10, NULL, NULL, NULL),
  ('着', 'n4'::nivel_jlpt, 3, 'llegar / ponerse (ropa)', 'ちゃく、じゃく', 'き.る、-ぎ、き.せる、-き.せ、つ.く、つ.ける', 12, NULL, NULL, NULL),
  ('終', 'n4'::nivel_jlpt, 3, 'terminar', 'しゅう', 'お.わる、-お.わる、おわ.る、お.える、つい、つい.に', 11, NULL, NULL, NULL),
  ('軽', 'n4'::nivel_jlpt, 3, 'ligero', 'けい、きょう、きん', 'かる.い、かろ.やか、かろ.んじる', 12, NULL, NULL, NULL),
  ('習', 'n4'::nivel_jlpt, 3, 'aprender / practicar', 'しゅう、じゅ', 'なら.う、なら.い', 11, NULL, NULL, NULL),
  ('発', 'n4'::nivel_jlpt, 3, 'salir / emitir', 'はつ、ほつ', 'た.つ、あば.く、おこ.る、つか.わす、はな.つ', 9, NULL, NULL, NULL),
  ('銀', 'n4'::nivel_jlpt, 3, 'plata', 'ぎん', 'しろがね', 14, NULL, NULL, NULL),
  ('代', 'n4'::nivel_jlpt, 3, 'generación / sustituir', 'だい、たい', 'か.わる、かわ.る、かわ.り、か.わり、-がわ.り、-が.わり、か.える、よ、しろ', 5, NULL, NULL, NULL),
  ('区', 'n4'::nivel_jlpt, 3, 'distrito / zona', 'く、おう、こう', NULL, 4, NULL, NULL, NULL),
  ('県', 'n4'::nivel_jlpt, 3, 'prefectura', 'けん', 'か.ける', 9, NULL, NULL, NULL),
  ('都', 'n4'::nivel_jlpt, 3, 'capital / metrópoli', 'と、つ', 'みやこ', 11, NULL, NULL, NULL),
  ('題', 'n4'::nivel_jlpt, 3, 'tema / título', 'だい', NULL, 18, NULL, NULL, NULL),
  ('業', 'n4'::nivel_jlpt, 3, 'negocio / ocupación', 'ぎょう、ごう', 'わざ', 13, NULL, NULL, NULL),
  ('試', 'n4'::nivel_jlpt, 4, 'probar / examen', 'し', 'こころ.みる、ため.す', 13, NULL, NULL, NULL),
  ('験', 'n4'::nivel_jlpt, 4, 'experimentar / examen', 'けん、げん', 'あかし、しるし、ため.す、ためし', 18, NULL, NULL, NULL),
  ('説', 'n4'::nivel_jlpt, 4, 'explicar / teoría', 'せつ、ぜい', 'と.く', 14, NULL, NULL, NULL),
  ('産', 'n4'::nivel_jlpt, 4, 'producir / dar a luz', 'さん', 'う.む、う.まれる、うぶ-、む.す', 11, NULL, NULL, NULL),
  ('飯', 'n4'::nivel_jlpt, 4, 'arroz cocido / comida', 'はん', 'めし', 12, NULL, NULL, NULL),
  ('無', 'n4'::nivel_jlpt, 4, 'nada / sin', 'む、ぶ', 'な.い', 12, NULL, NULL, NULL),
  ('以', 'n4'::nivel_jlpt, 4, 'a partir de / mediante', 'い', 'もっ.て', 5, NULL, NULL, NULL),
  ('英', 'n4'::nivel_jlpt, 4, 'inglés / Inglaterra', 'えい', 'はなぶさ', 8, NULL, NULL, NULL),
  ('民', 'n4'::nivel_jlpt, 4, 'pueblo / ciudadano', 'みん', 'たみ', 5, NULL, NULL, NULL),
  ('借', 'n4'::nivel_jlpt, 4, 'pedir prestado', 'しゃく', 'か.りる', 10, NULL, NULL, NULL),
  ('便', 'n4'::nivel_jlpt, 4, 'conveniente / correo', 'べん、びん', 'たよ.り', 9, NULL, NULL, NULL),
  ('不', 'n4'::nivel_jlpt, 4, 'no / negativo', 'ふ、ぶ', NULL, 4, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/not,%20non-.webp'),
  ('好', 'n4'::nivel_jlpt, 4, 'gustar / bueno', 'こう', 'この.む、す.く、よ.い、い.い', 6, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/to%20like.webp'),
  ('働', 'n4'::nivel_jlpt, 4, 'trabajar', 'どう', 'はたら.く', 13, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/to%20work.webp'),
  ('低', 'n4'::nivel_jlpt, 4, 'bajo', 'てい', 'ひく.い、ひく.める、ひく.まる', 7, NULL, NULL, NULL),
  ('菜', 'n4'::nivel_jlpt, 4, 'verdura', 'さい', 'な', 11, NULL, NULL, NULL),
  ('料', 'n4'::nivel_jlpt, 4, 'tarifa / material', 'りょう', NULL, 10, NULL, NULL, NULL),
  ('特', 'n4'::nivel_jlpt, 4, 'especial', 'とく', NULL, 10, NULL, NULL, NULL),
  ('別', 'n4'::nivel_jlpt, 4, 'separado / diferente', 'べつ', 'わか.れる、わ.ける', 7, NULL, NULL, NULL),
  ('堂', 'n4'::nivel_jlpt, 5, 'salón / templo', 'どう', NULL, 11, NULL, NULL, NULL),
  ('貸', 'n4'::nivel_jlpt, 5, 'prestar', 'たい', 'か.す、か.し-、かし-', 12, NULL, NULL, NULL),
  ('私', 'n4'::nivel_jlpt, 6, 'yo / privado', 'し', 'わたくし、わたし', 7, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/i%20(watashi).webp'),
  ('洗', 'n4'::nivel_jlpt, 6, 'lavar', 'せん', 'あら.う', 9, NULL, NULL, '/images/projects/all-about-kanjis/mnemotecnias/n4/to%20wash.webp'),
  ('映', 'n4'::nivel_jlpt, 6, 'reflejar / proyectar', 'えい', 'うつ.る、うつ.す、は.える、-ば.え', 9, NULL, NULL, NULL),
  ('研', 'n4'::nivel_jlpt, 3, 'pulir / investigar (研究 = investigación)', 'けん', 'と.ぐ', 9, NULL, NULL, NULL),
  ('究', 'n4'::nivel_jlpt, 3, 'investigar a fondo', 'きゅう、く', 'きわ.める', 7, NULL, NULL, NULL),
  ('建', 'n4'::nivel_jlpt, 4, 'construir', 'けん、こん', 'た.てる、た.て、-だ.て、た.つ', 9, NULL, NULL, NULL),
  ('有', 'n4'::nivel_jlpt, 3, 'tener / existir', 'ゆう、う', 'あ.る', 6, NULL, NULL, NULL),
  ('度', 'n4'::nivel_jlpt, 3, 'grado / vez / medida', 'ど、と、たく', 'たび、-た.い', 9, NULL, NULL, NULL),
  ('質', 'n4'::nivel_jlpt, 5, 'calidad / naturaleza', 'しつ、しち、ち', 'たち、ただ.す、もと、わりふ', 15, NULL, NULL, NULL)
ON CONFLICT (caracter) DO UPDATE SET
  nivel = EXCLUDED.nivel,
  anio_escolar_japon = EXCLUDED.anio_escolar_japon,
  significado = EXCLUDED.significado,
  numero_trazos = EXCLUDED.numero_trazos,
  onyomi = EXCLUDED.onyomi,
  kunyomi = EXCLUDED.kunyomi,
  url_imagen_mnemotecnica = EXCLUDED.url_imagen_mnemotecnica;
