-- ============================================================
-- SEED: personas famosas N4 (1 por kanji, 184 kanjis)
-- ============================================================
--
-- Persona o personaje conocido cuyo nombre contiene el kanji. Mezcla
-- figuras historicas, actores, mangakas y personajes de anime/manga/juegos.
-- Cada entrada tiene una descripcion corta en español para dar contexto.
--
-- Formato de cada fila (caracter, nombre, descripcion):
--   caracter    -> kanji origen para joinear con kanji.id
--   nombre      -> nombre completo (con kanji cuando corresponde)
--   descripcion -> breve resumen del rol o razon de fama
--
-- Idempotente: primero borra todas las personas existentes de los kanjis
-- cargados como n4, luego inserta el listado completo.
-- --------------------------------------------------------------

DELETE FROM personas_famosas
WHERE kanji_id IN (
  SELECT id FROM kanji WHERE nivel = 'n4'::nivel_jlpt
);

INSERT INTO personas_famosas (kanji_id, nombre, descripcion)
SELECT k.id, v.nombre, v.descripcion
FROM (VALUES
  ('正', '正岡子規', 'poeta de haiku de la era Meiji (1867-1902)'),
  ('早', '早川雪洲', 'primer actor japonés estrella en Hollywood (1886-1973)'),
  ('赤', '赤坂アカ', 'mangaka creador de Kaguya-sama: Love is War'),
  ('青', '青山剛昌', 'mangaka creador de Detective Conan (Meitantei Conan)'),
  ('犬', '犬夜叉', 'protagonista mitad demonio del manga/anime InuYasha de Rumiko Takahashi'),
  ('田', '田中角栄', 'primer ministro japonés (1972-1974), figura central del s.XX'),
  ('町', '町田啓太', 'actor japonés contemporáneo, exmiembro de The Rampage'),
  ('夕', '夕立', 'destructor personificado como chica del juego Kantai Collection'),
  ('文', '文豪ストレイドッグス', 'manga/anime donde escritores clásicos poseen habilidades sobrenaturales'),
  ('字', '十文字弥彦', 'antagonista del anime Rurouni Kenshin, líder de un grupo criminal'),
  ('音', '初音ミク', 'cantante virtual Vocaloid de Crypton Future Media, ícono global desde 2007'),
  ('力', '力道山', 'luchador profesional legendario de la posguerra japonesa (1924-1963)'),
  ('林', '小林幸子', 'cantante enka famosa por sus vestuarios extravagantes en el Kōhaku'),
  ('森', '森鴎外', 'novelista y médico militar de la era Meiji, autor de Maihime (1862-1922)'),
  ('村', '木村拓哉', 'actor y cantante, exlíder del grupo idol SMAP'),
  ('強', '強力伝', 'novela de Nitta Jirō (1955) sobre porteadores de montaña, premio Naoki'),
  ('弱', '弱虫ペダル', 'manga y anime sobre ciclismo en preparatoria de Wataru Watanabe'),
  ('楽', '一条楽', 'protagonista del manga romántico Nisekoi de Naoshi Komi'),
  ('春', '春野サクラ', 'kunoichi del Equipo 7 en el manga/anime Naruto'),
  ('夏', '夏目漱石', 'novelista Meiji autor de Kokoro y Wagahai wa Neko de Aru'),
  ('秋', '秋元康', 'productor y letrista, creador de AKB48 y sus grupos hermanos'),
  ('冬', '冬月コウゾウ', 'subcomandante de Nerv en Neon Genesis Evangelion'),
  ('色', '色川武大', 'escritor japonés (1929-1989), autor de novelas sobre apuestas'),
  ('黒', '黒澤明', 'director de cine legendario (Los siete samurái, Rashōmon)'),
  ('茶', '茶々', 'concubina de Toyotomi Hideyoshi, madre de Hideyori, también llamada Yodo-dono'),
  ('兄', '兄ちゃんはおしまい！', 'manga y anime de comedia sobre un hermano transformado en hermana menor'),
  ('弟', '弟の夫', 'manga LGBT+ de Tagame Gengoroh sobre un hombre y su cuñado gay canadiense'),
  ('姉', '姉さん、事件です！', 'dorama japonés de comedia sobre una asistenta y un profesor'),
  ('妹', '妹さえいればいい。', 'light novel de Yomi Hirasaka sobre un escritor obsesionado con la imouto'),
  ('牛', '牛若丸', 'nombre de infancia de Minamoto no Yoshitsune, héroe del período Heian'),
  ('鳥', '鳥山明', 'mangaka creador de Dragon Ball y Dr. Slump (1955-2024)'),
  ('地', '地獄少女', 'anime de terror sobre venganza sobrenatural vía web'),
  ('京', '京極夏彦', 'novelista de misterio y folclore japonés (Ubume no Natsu)'),
  ('門', '近松門左衛門', 'dramaturgo Edo del bunraku y kabuki (1653-1725)'),
  ('晴', '安倍晴明', 'onmyōji legendario del período Heian, maestro de adivinación'),
  ('家', '徳川家康', 'primer shōgun del shogunato Tokugawa (1543-1616)'),
  ('方', '北方謙三', 'novelista de crímenes y sagas históricas contemporáneo'),
  ('光', '光源氏', 'protagonista de Genji Monogatari de Murasaki Shikibu'),
  ('海', '海堂尊', 'novelista médico contemporáneo, autor de la saga Chirurgien Team Batista'),
  ('台', '仙台四郎', 'personaje histórico de Sendai (Meiji), considerado talismán de suerte'),
  ('室', '室井滋', 'actriz y ensayista japonesa contemporánea'),
  ('朝', '朝倉未来', 'luchador de artes marciales mixtas y youtuber japonés'),
  ('昼', '昼顔', 'dorama japonés de 2014 sobre infidelidad conyugal'),
  ('夜', '夜神月', 'protagonista de Death Note, escribe nombres en el cuaderno mortal'),
  ('回', '回復術士のやり直し', 'light novel y anime isekai controversial sobre venganza'),
  ('池', '池上彰', 'periodista y presentador conocido por sus explicaciones de noticias'),
  ('作', '山田耕作', 'compositor japonés (1886-1965), pionero de la música clásica japonesa'),
  ('走', '走れメロス', 'cuento de Osamu Dazai de 1940, lectura obligatoria en escuelas japonesas'),
  ('首', '首藤剛志', 'guionista de anime, escribió los primeros episodios de Pokémon'),
  ('売', '即売会', 'convenciones doujin donde artistas venden sus obras (ej. Comiket)'),
  ('止', '遣唐使の廃止', 'fin de las misiones japonesas a la China Tang (894), propuesto por Sugawara no Michizane'),
  ('親', '親鸞', 'monje budista (1173-1263), fundador de la escuela Jōdo Shinshū'),
  ('市', '市原悦子', 'actriz de voz de Nihon Mukashibanashi, narró más de 1500 cuentos'),
  ('引', '引田天功', 'ilusionista japonesa conocida internacionalmente como Princess Tenko'),
  ('太', '太宰治', 'novelista clásico (Ningen Shikkaku, Hashire Melos), suicida en 1948'),
  ('合', '合気道', 'arte marcial fundado por Morihei Ueshiba en los años 1920'),
  ('遠', '遠藤周作', 'novelista de Silencio (Chinmoku), obra sobre cristianos ocultos en Japón'),
  ('近', '近藤麻理恵', 'consultora de organización mundialmente famosa por el método KonMari'),
  ('広', '広瀬すず', 'actriz japonesa contemporánea'),
  ('明', '明石家さんま', 'comediante icónico del お笑いBIG3'),
  ('切', '切腹', 'film clásico de Masaki Kobayashi (1962) sobre un samurái en un tribunal Edo'),
  ('心', '緋村剣心', 'espadachín protagonista del manga/anime Rurouni Kenshin'),
  ('体', '三体', 'novela de ciencia ficción de Liu Cixin, traducida al japonés y adaptada al anime'),
  ('同', '同期のサクラ', 'dorama japonés (2019) sobre trabajadores de una constructora'),
  ('自', '自来也', 'sennin sabio de los sapos, maestro de Naruto Uzumaki'),
  ('肉', 'キン肉マン', 'superhéroe de la lucha libre en el manga clásico de Yudetamago'),
  ('工', '工藤新一', 'detective adolescente protagonista de Detective Conan'),
  ('公', '公文公', 'fundador del método educativo Kumon (1914-1995)'),
  ('元', '元寇', 'dos invasiones fallidas de la dinastía Yuan a Japón (1274, 1281), detenidas por los kamikaze'),
  ('風', '風の谷のナウシカ', 'primer film de Studio Ghibli, dirigido por Hayao Miyazaki (1984)'),
  ('声', '声の形', 'film animado (2016) de Naoko Yamada sobre bullying y sordera'),
  ('曜', '土曜ワイド劇場', 'bloque de películas de misterio de TV Asahi (1977-2017)'),
  ('思', '思い出のマーニー', 'película de Ghibli (2014) dirigida por Hiromasa Yonebayashi'),
  ('知', '松平信綱', 'consejero samurai (1596-1662), apodado Chie-Izu (Izu el Sabio)'),
  ('通', '通天閣', 'torre emblemática de Osaka construida en 1912, símbolo de Shinsekai'),
  ('顔', '顔', 'film noir japonés de 1957 dirigido por Hideo Ōba'),
  ('頭', '頭文字D', 'manga y anime de Shūichi Shigeno sobre carreras callejeras en Gunma'),
  ('歩', '上原歩夢', 'idol del anime Love Live! Nijigasaki High School Idol Club'),
  ('歌', '歌川広重', 'pintor ukiyo-e del período Edo, autor de las 53 estaciones del Tōkaidō'),
  ('図', '伊能忠敬', 'cartógrafo Edo, autor del primer mapa científico de Japón (1821)'),
  ('画', '映画クレヨンしんちゃん', 'saga de películas anuales del anime Crayon Shin-chan desde 1993'),
  ('計', '時計仕掛けの林檎', 'manga corto de Osamu Tezuka influenciado por A Clockwork Orange'),
  ('場', '馬場信春', 'general samurai al servicio de Takeda Shingen (1515-1575)'),
  ('考', '考える人', 'escultura icónica de Auguste Rodin, muy popularizada en Japón'),
  ('野', '野茂英雄', 'primer beisbolista japonés estrella en la MLB (Dodgers, Mets)'),
  ('理', '理系が恋に落ちたので証明してみた', 'light novel y anime cómico sobre científicos que intentan probar el amor'),
  ('答', '答えのない歌', 'canción de la banda japonesa BUMP OF CHICKEN'),
  ('教', '暗殺教室', 'manga y anime de Yūsei Matsui sobre estudiantes que deben asesinar a su profesor pulpo'),
  ('帰', '帰りたくなったよ', 'sencillo de 2009 del grupo pop Ikimonogakari'),
  ('紙', '折り紙', 'arte japonés de plegado de papel, con figuras clásicas como la grulla'),
  ('用', '用心棒', 'film samurái clásico de Akira Kurosawa (1961) con Toshirō Mifune'),
  ('薬', '薬師丸ひろ子', 'actriz y cantante de los 80, conocida por Sailor Suit and Machine Gun'),
  ('重', '田中久重', 'inventor Edo/Meiji, fundador de la empresa que se convirtió en Toshiba'),
  ('者', '勇者ヨシヒコと魔王の城', 'dorama japonés de parodia RPG (2011-2016) protagonizado por Takayuki Yamada'),
  ('待', '待つわ', 'sencillo icónico de 1982 del dúo Amin'),
  ('持', '持田香織', 'vocalista del grupo J-pop Every Little Thing'),
  ('動', '機動戦士ガンダム', 'saga de mecha creada por Yoshiyuki Tomino en 1979, seminal del género'),
  ('始', '秦の始皇帝', 'primer emperador de China (259-210 a.C.), ordenó construir la Gran Muralla'),
  ('暑', '暑中見舞い', 'postal tradicional japonesa de saludo veraniego enviada durante 大暑'),
  ('寒', '大寒', 'uno de los 24 términos solares (~20 enero), día más frío del año'),
  ('味', '味の素', 'empresa japonesa fundada en 1909, creadora del monosodio glutamato'),
  ('開', '開高健', 'novelista y reportero de guerra japonés en Vietnam (1930-1989)'),
  ('問', '問題児たちが異世界から来るそうですよ？', 'light novel y anime isekai sobre niños problemáticos con poderes'),
  ('運', '運慶', 'escultor budista del período Kamakura, autor de las estatuas del Nandaimon de Tōdai-ji'),
  ('転', '転生したらスライムだった件', 'light novel/anime isekai de Fuse sobre un hombre reencarnado como slime'),
  ('品', '品川ヒロシ', 'comediante del dúo Shinagawa Shōji, también director de cine'),
  ('屋', '土屋太鳳', 'actriz japonesa contemporánea'),
  ('急', '阪急電鉄', 'compañía ferroviaria de Osaka fundada en 1907'),
  ('意', '意地悪ばあさん', 'manga de Machiko Hasegawa (autora de Sazae-san) sobre una anciana traviesa'),
  ('悪', '悪魔のリドル', 'manga y anime sobre asesinas en un aula de niñas'),
  ('暗', '暗黒神話', 'manga de horror mitológico de Daijirō Morohoshi (1976)'),
  ('世', '世阿弥', 'dramaturgo Noh (~1363-1443), autor de Fūshi Kaden'),
  ('界', '境界のRINNE', 'manga de Rumiko Takahashi (2009-2017) sobre un shinigami adolescente'),
  ('住', '住友政友', 'fundador del clan mercantil Sumitomo en el s.XVII'),
  ('洋', '島田洋七', 'comediante del dúo Shimada Yōshichi & Yōhachi, autor de Saga no Gabai Bāchan'),
  ('注', '注文の多い料理店', 'cuento clásico de Kenji Miyazawa (1924)'),
  ('死', 'BLEACH', 'manga y anime de Tite Kubo sobre shinigami que protegen almas'),
  ('漢', '日本漢字能力検定', 'examen nacional de kanji con 12 niveles, del 10級 al 1級'),
  ('主', '中村主水', 'personaje icónico de la saga Hissatsu (1973-), samurái asesino a sueldo'),
  ('送', '日本放送協会', 'cadena pública de radio y TV de Japón (NHK), fundada en 1926'),
  ('進', '進撃の巨人', 'manga de Hajime Isayama (2009-2021), obra icónica de la era'),
  ('去', '過去のない男', 'título japonés del film The Man Without a Past (2002) de Aki Kaurismäki'),
  ('集', '万葉集', 'antología poética más antigua de Japón (s.VIII), unos 4500 waka'),
  ('起', '起き上がり小法師', 'muñeco tradicional (daruma) de Fukushima que se levanta solo'),
  ('勉', '僕たちは勉強ができない', 'manga y anime de Taishi Tsutsui, comedia romántica de tutorías'),
  ('写', '東洲斎写楽', 'enigmático artista ukiyo-e activo solo diez meses en 1794-1795'),
  ('真', '真田幸村', 'samurái legendario del Sengoku, murió en el Sitio de Osaka (1615)'),
  ('仕', 'プロフェッショナル仕事の流儀', 'programa NHK que retrata profesionales destacados desde 2006'),
  ('事', '金田一少年の事件簿', 'manga clásico de detectives (1992-) de Kanari y Satō'),
  ('館', '小学館', 'editorial de manga fundada en 1922 (Doraemon, Detective Conan)'),
  ('服', 'セーラー服と機関銃', 'novela y film de 1981 con Yakushimaru Hiroko, dirigida por Shinji Sōmai'),
  ('院', '後鳥羽院', 'emperador y poeta waka del período Kamakura (1180-1239)'),
  ('病', '病院坂の首縊りの家', 'novela detectivesca de Seishi Yokomizo (1975-1978), última obra de Kindaichi'),
  ('医', '医龍-Team Medical Dragon-', 'manga y dorama médico sobre cirujanos elite en un hospital universitario'),
  ('使', '使徒', 'seres misteriosos que atacan Tokio-3 en Neon Genesis Evangelion'),
  ('旅', 'キノの旅', 'light novel de Keiichi Sigsawa sobre una viajera pensativa en países distópicos'),
  ('族', '暴走族', 'subcultura japonesa de motociclistas rebeldes, popular en los años 70-80'),
  ('所', '宇宙よりも遠い場所', 'anime original (2018) sobre chicas viajando a la Antártida'),
  ('乗', '乗鞍岳', 'montaña volcánica de 3026m en los Alpes japoneses, popular para senderismo'),
  ('物', '化物語', 'serie de novelas ligeras de Nisio Isin adaptadas al anime por SHAFT'),
  ('短', '短歌', 'forma poética tradicional japonesa de 5-7-5-7-7 sílabas'),
  ('員', '駅員', 'personal ferroviario, símbolo de la cultura laboral japonesa por su cortesía'),
  ('着', 'その着せ替え人形は恋をする', 'manga y anime de Shinichi Fukuda sobre cosplay y romance'),
  ('終', '終末のワルキューレ', 'manga (2017-) de dioses contra humanos en un torneo apocalíptico'),
  ('軽', '軽井沢', 'pueblo de veraneo en Nagano, popular entre aristocracia y celebridades'),
  ('習', '学習塾', 'institución privada de refuerzo escolar, presente en todo Japón'),
  ('発', '発明王エジソン', 'apodo japonés de Thomas Edison, símbolo de la invención'),
  ('銀', '銀魂', 'manga y anime de comedia de Hideaki Sorachi sobre samuráis en un Edo alterno'),
  ('代', '代々木', 'distrito de Shibuya (Tokio) famoso por su parque y la sede de NHK'),
  ('区', '東京23区', 'los 23 distritos especiales del centro de Tokio'),
  ('県', '都道府県かるた', 'karuta educativo japonés para memorizar las 47 prefecturas'),
  ('都', '京都議定書', 'tratado climático internacional firmado en Kioto en 1997'),
  ('題', '題名のない音楽会', 'programa musical de TV Asahi (1964-), el más longevo del género en Japón'),
  ('業', '業田良家', 'mangaka japonés, autor de Jigyaku no Uta y Kikai Jikake no Ai'),
  ('試', '試験の花道', 'programa NHK educativo (2008-2016) con consejos de estudio para exámenes'),
  ('験', '経験値', 'puntos de experiencia en juegos de rol japoneses, clave en la mecánica JRPG'),
  ('説', '小説家になろう', 'plataforma web (2004) donde debutan la mayoría de light novels e isekai'),
  ('産', '日産自動車', 'fabricante japonés de automóviles fundado en 1933'),
  ('飯', '花のずぼら飯', 'manga cómico sobre una esposa perezosa que cocina rápido'),
  ('無', '鬼滅の刃 無限列車編', 'arco y film de Demon Slayer, taquillazo mundial de 2020'),
  ('以', '岡田以蔵', 'hitokiri del Bakumatsu (1838-1865), asesino al servicio de Tosa'),
  ('英', '英一蝶', 'pintor Edo (1652-1724) del estilo Kanō, célebre por escenas costumbristas'),
  ('民', '柳田國男', 'fundador del folklore japonés (民俗学), autor de Tōno Monogatari (1875-1962)'),
  ('借', '借りぐらしのアリエッティ', 'film Ghibli (2010) dirigido por Hiromasa Yonebayashi'),
  ('便', '魔女の宅急便', 'film Ghibli (1989) de Hayao Miyazaki basado en la novela de Eiko Kadono'),
  ('不', '藤子・F・不二雄', 'mangaka (1933-1996) creador de Doraemon, Perman y Kiteretsu Daihyakka'),
  ('好', '好きっていいなよ。', 'manga shōjo de Kanae Hazuki (2008-2017), romance escolar'),
  ('働', '働きマン', 'manga de Moyoco Anno sobre una editora de revista adicta al trabajo'),
  ('低', '最低賃金制度', 'sistema legal japonés que fija salarios mínimos por prefectura'),
  ('菜', '菜々緒', 'modelo y actriz japonesa contemporánea'),
  ('料', '料理の鉄人', 'programa culinario de Fuji TV (1993-1999), pionero del reality gastronómico'),
  ('特', '特撮', 'género japonés de efectos especiales prácticos (Godzilla, Ultraman, Kamen Rider)'),
  ('別', '別役実', 'dramaturgo japonés (1937-2020) del teatro del absurdo'),
  ('堂', '三十三間堂', 'templo de Kioto con 1001 estatuas de Kannon, tesoro nacional'),
  ('貸', '貸本漫画', 'manga de alquiler popular en los 50s-60s, cuna de artistas como Mizuki Shigeru'),
  ('私', '私の履歴書', 'columna del diario Nikkei donde figuras destacadas cuentan sus memorias'),
  ('洗', '洗馬宿', 'antigua estación del Nakasendō en Shiojiri (Nagano), la N°31 de 69'),
  ('映', '東映アニメーション', 'estudio de animación fundado en 1948, productor de Dragon Ball y One Piece'),
  ('研', '羽賀研二', 'actor y tarento japonés, famoso en los años 80'),
  ('究', '究極超人あ〜る', 'manga cómico de culto de Yūichi Yūki (1985-1987)'),
  ('建', '建仁寺', 'templo Rinzai zen de Kioto (1202), el más antiguo de la escuela'),
  ('有', '有頂天家族', 'novela de Tomihiko Morimi (2007) y anime sobre tanuki en Kioto'),
  ('度', '度会家行', 'teólogo Shintō de Ise (1256-1362), fundador del Ise Shintō'),
  ('質', '質屋', 'casas de empeño tradicionales japonesas, existían desde el período Edo')
) AS v(caracter, nombre, descripcion)
JOIN kanji k ON k.caracter = v.caracter;
