-- ============================================================
-- SEED: palabras famosas N4 (3 palabras por kanji, 184 kanjis)
-- ============================================================
--
-- Companion del seed_kanji_n4. Se agregan palabras comunes (vocabulario
-- N5-N4 tipico) para cada kanji cargado en la BDD como nivel n4.
--
-- Formato de cada fila (caracter, palabra, furigana, traduccion):
--   caracter    -> kanji origen (varchar 1, se usa para joinear con kanji.id)
--   palabra     -> palabra escrita con kanji (o mixta con hiragana)
--   furigana    -> lectura COMPLETA de la palabra en hiragana (no solo
--                  la parte del kanji)
--   traduccion  -> significado en español
--
-- Idempotente: primero borra todas las palabras existentes de los kanjis
-- cargados como n4, luego inserta el listado completo. Correr las veces
-- que sea necesario sin dejar duplicados.
--
-- NOTA: el DELETE solo afecta a palabras cuyo kanji_id pertenece a
-- nivel = 'n4'. Palabras de kanjis n5 u otros niveles no se tocan.
-- --------------------------------------------------------------

DELETE FROM palabras_famosas
WHERE kanji_id IN (
  SELECT id FROM kanji WHERE nivel = 'n4'::nivel_jlpt
);

INSERT INTO palabras_famosas (kanji_id, palabra, furigana, traduccion)
SELECT k.id, v.palabra, v.furigana, v.traduccion
FROM (VALUES
  ('正', '正しい', 'ただしい', 'correcto'),
  ('正', '正解', 'せいかい', 'respuesta correcta'),
  ('正', '正月', 'しょうがつ', 'año nuevo japonés'),
  ('早', '早い', 'はやい', 'temprano / rápido'),
  ('早', '早朝', 'そうちょう', 'temprano en la mañana'),
  ('早', '早口', 'はやくち', 'hablar rápido'),
  ('赤', '赤い', 'あかい', 'rojo'),
  ('赤', '赤ちゃん', 'あかちゃん', 'bebé'),
  ('赤', '赤外線', 'せきがいせん', 'rayos infrarrojos'),
  ('青', '青い', 'あおい', 'azul'),
  ('青', '青年', 'せいねん', 'joven / juventud'),
  ('青', '青空', 'あおぞら', 'cielo azul'),
  ('犬', '犬', 'いぬ', 'perro'),
  ('犬', '子犬', 'こいぬ', 'cachorro'),
  ('犬', '番犬', 'ばんけん', 'perro guardián'),
  ('田', '田んぼ', 'たんぼ', 'arrozal'),
  ('田', '田舎', 'いなか', 'campo / zona rural'),
  ('田', '水田', 'すいでん', 'arrozal inundado'),
  ('町', '町', 'まち', 'pueblo / ciudad'),
  ('町', '下町', 'したまち', 'zona antigua de la ciudad'),
  ('町', '町内', 'ちょうない', 'vecindario / barrio'),
  ('夕', '夕方', 'ゆうがた', 'atardecer'),
  ('夕', '夕食', 'ゆうしょく', 'cena'),
  ('夕', '夕日', 'ゆうひ', 'sol del atardecer'),
  ('文', '文', 'ぶん', 'oración / frase'),
  ('文', '文化', 'ぶんか', 'cultura'),
  ('文', '文法', 'ぶんぽう', 'gramática'),
  ('字', '字', 'じ', 'carácter / letra'),
  ('字', '漢字', 'かんじ', 'kanji'),
  ('字', '数字', 'すうじ', 'número'),
  ('音', '音', 'おと', 'sonido'),
  ('音', '音楽', 'おんがく', 'música'),
  ('音', '発音', 'はつおん', 'pronunciación'),
  ('力', '力', 'ちから', 'fuerza'),
  ('力', '電力', 'でんりょく', 'energía eléctrica'),
  ('力', '協力', 'きょうりょく', 'cooperación'),
  ('林', '林', 'はやし', 'arboleda / bosque pequeño'),
  ('林', '山林', 'さんりん', 'montañas y bosques'),
  ('林', '林業', 'りんぎょう', 'silvicultura'),
  ('森', '森', 'もり', 'bosque'),
  ('森', '森林', 'しんりん', 'bosque / floresta'),
  ('森', '密林', 'みつりん', 'jungla / selva'),
  ('村', '村', 'むら', 'aldea'),
  ('村', '村人', 'むらびと', 'aldeano'),
  ('村', '農村', 'のうそん', 'pueblo agrícola'),
  ('強', '強い', 'つよい', 'fuerte'),
  ('強', '勉強', 'べんきょう', 'estudio'),
  ('強', '強化', 'きょうか', 'fortalecimiento'),
  ('弱', '弱い', 'よわい', 'débil'),
  ('弱', '弱点', 'じゃくてん', 'punto débil'),
  ('弱', '弱虫', 'よわむし', 'cobarde / miedoso'),
  ('楽', '楽しい', 'たのしい', 'divertido'),
  ('楽', '音楽', 'おんがく', 'música'),
  ('楽', '気楽', 'きらく', 'relajado / sin preocupaciones'),
  ('春', '春', 'はる', 'primavera'),
  ('春', '春休み', 'はるやすみ', 'vacaciones de primavera'),
  ('春', '春分', 'しゅんぶん', 'equinoccio de primavera'),
  ('夏', '夏', 'なつ', 'verano'),
  ('夏', '夏休み', 'なつやすみ', 'vacaciones de verano'),
  ('夏', '真夏', 'まなつ', 'pleno verano'),
  ('秋', '秋', 'あき', 'otoño'),
  ('秋', '秋分', 'しゅうぶん', 'equinoccio de otoño'),
  ('秋', '秋風', 'あきかぜ', 'viento de otoño'),
  ('冬', '冬', 'ふゆ', 'invierno'),
  ('冬', '冬休み', 'ふゆやすみ', 'vacaciones de invierno'),
  ('冬', '冬眠', 'とうみん', 'hibernación'),
  ('色', '色', 'いろ', 'color'),
  ('色', '景色', 'けしき', 'paisaje'),
  ('色', '色々', 'いろいろ', 'varios / diversos'),
  ('黒', '黒い', 'くろい', 'negro'),
  ('黒', '黒板', 'こくばん', 'pizarra'),
  ('黒', '黒字', 'くろじ', 'superávit / números negros'),
  ('茶', 'お茶', 'おちゃ', 'té'),
  ('茶', '茶色', 'ちゃいろ', 'color marrón'),
  ('茶', '紅茶', 'こうちゃ', 'té negro'),
  ('兄', '兄', 'あに', 'hermano mayor (propio)'),
  ('兄', 'お兄さん', 'おにいさん', 'hermano mayor (ajeno)'),
  ('兄', '兄嫁', 'あによめ', 'esposa del hermano mayor'),
  ('弟', '弟', 'おとうと', 'hermano menor'),
  ('弟', '弟子', 'でし', 'discípulo'),
  ('弟', '義弟', 'ぎてい', 'cuñado menor'),
  ('姉', '姉', 'あね', 'hermana mayor (propia)'),
  ('姉', 'お姉さん', 'おねえさん', 'hermana mayor (ajena)'),
  ('姉', '姉御', 'あねご', 'hermana mayor (líder femenina)'),
  ('妹', '妹', 'いもうと', 'hermana menor'),
  ('妹', '姉妹', 'しまい', 'hermanas'),
  ('妹', '妹分', 'いもうとぶん', 'como una hermana menor'),
  ('牛', '牛', 'うし', 'vaca'),
  ('牛', '牛乳', 'ぎゅうにゅう', 'leche'),
  ('牛', '水牛', 'すいぎゅう', 'búfalo de agua'),
  ('鳥', '鳥', 'とり', 'pájaro'),
  ('鳥', '小鳥', 'ことり', 'pajarito'),
  ('鳥', '白鳥', 'はくちょう', 'cisne'),
  ('地', '地図', 'ちず', 'mapa'),
  ('地', '地下', 'ちか', 'subterráneo'),
  ('地', '地震', 'じしん', 'terremoto'),
  ('京', '東京', 'とうきょう', 'Tokio'),
  ('京', '京都', 'きょうと', 'Kioto'),
  ('京', '上京', 'じょうきょう', 'ir a la capital (Tokio)'),
  ('門', '門', 'もん', 'portón / puerta'),
  ('門', '入門', 'にゅうもん', 'introducción / iniciación'),
  ('門', '専門', 'せんもん', 'especialidad'),
  ('晴', '晴れ', 'はれ', 'despejado (clima)'),
  ('晴', '晴天', 'せいてん', 'día despejado'),
  ('晴', '快晴', 'かいせい', 'claro y despejado'),
  ('家', '家', 'いえ', 'casa'),
  ('家', '家族', 'かぞく', 'familia'),
  ('家', '作家', 'さっか', 'autor / escritor'),
  ('方', '方', 'ほう', 'dirección / lado'),
  ('方', '方法', 'ほうほう', 'método'),
  ('方', '両方', 'りょうほう', 'ambos lados'),
  ('光', '光', 'ひかり', 'luz'),
  ('光', '日光', 'にっこう', 'luz solar'),
  ('光', '観光', 'かんこう', 'turismo'),
  ('海', '海', 'うみ', 'mar'),
  ('海', '海外', 'かいがい', 'extranjero'),
  ('海', '海岸', 'かいがん', 'costa'),
  ('台', '台所', 'だいどころ', 'cocina'),
  ('台', '台風', 'たいふう', 'tifón'),
  ('台', '舞台', 'ぶたい', 'escenario / obra teatral'),
  ('室', '教室', 'きょうしつ', 'aula'),
  ('室', '寝室', 'しんしつ', 'dormitorio'),
  ('室', '浴室', 'よくしつ', 'cuarto de baño'),
  ('朝', '朝', 'あさ', 'mañana'),
  ('朝', '朝食', 'ちょうしょく', 'desayuno'),
  ('朝', '朝日', 'あさひ', 'sol de la mañana'),
  ('昼', '昼', 'ひる', 'mediodía'),
  ('昼', '昼食', 'ちゅうしょく', 'almuerzo'),
  ('昼', '昼寝', 'ひるね', 'siesta'),
  ('夜', '夜', 'よる', 'noche'),
  ('夜', '今夜', 'こんや', 'esta noche'),
  ('夜', '深夜', 'しんや', 'medianoche'),
  ('回', '一回', 'いっかい', 'una vez'),
  ('回', '回転', 'かいてん', 'rotación'),
  ('回', '今回', 'こんかい', 'esta vez'),
  ('池', '池', 'いけ', 'estanque'),
  ('池', '電池', 'でんち', 'batería'),
  ('池', '貯水池', 'ちょすいち', 'embalse'),
  ('作', '作る', 'つくる', 'hacer / fabricar'),
  ('作', '作品', 'さくひん', 'obra'),
  ('作', '作文', 'さくぶん', 'composición / redacción'),
  ('走', '走る', 'はしる', 'correr'),
  ('走', '競走', 'きょうそう', 'carrera / competencia'),
  ('走', '逃走', 'とうそう', 'fuga / escape'),
  ('首', '首', 'くび', 'cuello'),
  ('首', '首都', 'しゅと', 'capital'),
  ('首', '手首', 'てくび', 'muñeca'),
  ('売', '売る', 'うる', 'vender'),
  ('売', '売店', 'ばいてん', 'quiosco'),
  ('売', '販売', 'はんばい', 'venta / comercialización'),
  ('止', '止まる', 'とまる', 'detenerse'),
  ('止', '中止', 'ちゅうし', 'suspensión'),
  ('止', '禁止', 'きんし', 'prohibición'),
  ('親', '親', 'おや', 'padre o madre'),
  ('親', '両親', 'りょうしん', 'padres (ambos)'),
  ('親', '親切', 'しんせつ', 'amable / bondadoso'),
  ('市', '市', 'し', 'ciudad'),
  ('市', '市場', 'いちば', 'mercado'),
  ('市', '市民', 'しみん', 'ciudadano'),
  ('引', '引く', 'ひく', 'tirar / jalar'),
  ('引', '引退', 'いんたい', 'retiro'),
  ('引', '割引', 'わりびき', 'descuento'),
  ('太', '太い', 'ふとい', 'grueso'),
  ('太', '太陽', 'たいよう', 'sol'),
  ('太', '丸太', 'まるた', 'tronco'),
  ('合', '合う', 'あう', 'coincidir / quedar bien'),
  ('合', '合図', 'あいず', 'señal'),
  ('合', '合格', 'ごうかく', 'aprobar un examen'),
  ('遠', '遠い', 'とおい', 'lejano'),
  ('遠', '遠足', 'えんそく', 'excursión'),
  ('遠', '望遠鏡', 'ぼうえんきょう', 'telescopio'),
  ('近', '近い', 'ちかい', 'cercano'),
  ('近', '最近', 'さいきん', 'recientemente'),
  ('近', '近所', 'きんじょ', 'vecindario'),
  ('広', '広い', 'ひろい', 'amplio / espacioso'),
  ('広', '広告', 'こうこく', 'anuncio'),
  ('広', '広場', 'ひろば', 'plaza / explanada'),
  ('明', '明るい', 'あかるい', 'brillante / alegre'),
  ('明', '説明', 'せつめい', 'explicación'),
  ('明', '明日', 'あした', 'mañana (día siguiente)'),
  ('切', '切る', 'きる', 'cortar'),
  ('切', '大切', 'たいせつ', 'importante'),
  ('切', '切符', 'きっぷ', 'billete / boleto'),
  ('心', '心', 'こころ', 'corazón / mente'),
  ('心', '中心', 'ちゅうしん', 'centro'),
  ('心', '安心', 'あんしん', 'tranquilidad'),
  ('体', '体', 'からだ', 'cuerpo'),
  ('体', '体育', 'たいいく', 'educación física'),
  ('体', '全体', 'ぜんたい', 'totalidad / conjunto'),
  ('同', '同じ', 'おなじ', 'igual'),
  ('同', '同時', 'どうじ', 'al mismo tiempo'),
  ('同', '同僚', 'どうりょう', 'colega'),
  ('自', '自分', 'じぶん', 'uno mismo'),
  ('自', '自転車', 'じてんしゃ', 'bicicleta'),
  ('自', '自由', 'じゆう', 'libertad'),
  ('肉', '肉', 'にく', 'carne'),
  ('肉', '牛肉', 'ぎゅうにく', 'carne de res'),
  ('肉', '筋肉', 'きんにく', 'músculo'),
  ('工', '工場', 'こうじょう', 'fábrica'),
  ('工', '工事', 'こうじ', 'obras / construcción'),
  ('工', '大工', 'だいく', 'carpintero'),
  ('公', '公園', 'こうえん', 'parque'),
  ('公', '公立', 'こうりつ', 'público (institución)'),
  ('公', '公務員', 'こうむいん', 'funcionario público'),
  ('元', '元気', 'げんき', 'saludable / con energía'),
  ('元', '元', 'もと', 'origen / raíz'),
  ('元', '地元', 'じもと', 'lugar de origen / localidad'),
  ('風', '風', 'かぜ', 'viento'),
  ('風', '台風', 'たいふう', 'tifón'),
  ('風', '風邪', 'かぜ', 'resfriado'),
  ('声', '声', 'こえ', 'voz'),
  ('声', '大声', 'おおごえ', 'voz alta / grito'),
  ('声', '音声', 'おんせい', 'audio / voz'),
  ('曜', '月曜日', 'げつようび', 'lunes'),
  ('曜', '曜日', 'ようび', 'día de la semana'),
  ('曜', '日曜日', 'にちようび', 'domingo'),
  ('思', '思う', 'おもう', 'pensar'),
  ('思', '思い出', 'おもいで', 'recuerdo'),
  ('思', '意思', 'いし', 'voluntad / intención'),
  ('知', '知る', 'しる', 'saber / conocer'),
  ('知', '知識', 'ちしき', 'conocimiento'),
  ('知', '知り合い', 'しりあい', 'conocido'),
  ('通', '通る', 'とおる', 'pasar'),
  ('通', '交通', 'こうつう', 'tráfico / transporte'),
  ('通', '通学', 'つうがく', 'ir a la escuela'),
  ('顔', '顔', 'かお', 'cara'),
  ('顔', '顔色', 'かおいろ', 'aspecto / color de cara'),
  ('顔', '笑顔', 'えがお', 'sonrisa'),
  ('頭', '頭', 'あたま', 'cabeza'),
  ('頭', '先頭', 'せんとう', 'cabeza / delante'),
  ('頭', '頭痛', 'ずつう', 'dolor de cabeza'),
  ('歩', '歩く', 'あるく', 'caminar'),
  ('歩', '散歩', 'さんぽ', 'paseo'),
  ('歩', '歩道', 'ほどう', 'acera / vereda'),
  ('歌', '歌', 'うた', 'canción'),
  ('歌', '歌手', 'かしゅ', 'cantante'),
  ('歌', '国歌', 'こっか', 'himno nacional'),
  ('図', '地図', 'ちず', 'mapa'),
  ('図', '図書館', 'としょかん', 'biblioteca'),
  ('図', '図形', 'ずけい', 'figura geométrica'),
  ('画', '映画', 'えいが', 'película'),
  ('画', '画家', 'がか', 'pintor'),
  ('画', '漫画', 'まんが', 'manga / historieta'),
  ('計', '時計', 'とけい', 'reloj'),
  ('計', '計画', 'けいかく', 'plan'),
  ('計', '会計', 'かいけい', 'contabilidad'),
  ('場', '場所', 'ばしょ', 'lugar'),
  ('場', '会場', 'かいじょう', 'lugar del evento'),
  ('場', '職場', 'しょくば', 'lugar de trabajo'),
  ('考', '考える', 'かんがえる', 'pensar / considerar'),
  ('考', '参考', 'さんこう', 'referencia'),
  ('考', '思考', 'しこう', 'pensamiento'),
  ('野', '野菜', 'やさい', 'verdura'),
  ('野', '野球', 'やきゅう', 'béisbol'),
  ('野', '野原', 'のはら', 'campo / pradera'),
  ('理', '理由', 'りゆう', 'razón / motivo'),
  ('理', '料理', 'りょうり', 'cocina / plato'),
  ('理', '心理', 'しんり', 'psicología'),
  ('答', '答える', 'こたえる', 'responder'),
  ('答', '答え', 'こたえ', 'respuesta'),
  ('答', '回答', 'かいとう', 'respuesta / réplica'),
  ('教', '教える', 'おしえる', 'enseñar'),
  ('教', '教室', 'きょうしつ', 'aula'),
  ('教', '教科書', 'きょうかしょ', 'libro de texto'),
  ('帰', '帰る', 'かえる', 'regresar / volver'),
  ('帰', '帰国', 'きこく', 'regreso al país'),
  ('帰', '帰宅', 'きたく', 'volver a casa'),
  ('紙', '紙', 'かみ', 'papel'),
  ('紙', '手紙', 'てがみ', 'carta'),
  ('紙', '表紙', 'ひょうし', 'portada'),
  ('用', '用事', 'ようじ', 'asunto / diligencia'),
  ('用', '使用', 'しよう', 'uso'),
  ('用', '用意', 'ようい', 'preparación'),
  ('薬', '薬', 'くすり', 'medicina'),
  ('薬', '薬局', 'やっきょく', 'farmacia'),
  ('薬', '薬草', 'やくそう', 'hierba medicinal'),
  ('重', '重い', 'おもい', 'pesado'),
  ('重', '重要', 'じゅうよう', 'importante'),
  ('重', '体重', 'たいじゅう', 'peso corporal'),
  ('者', '医者', 'いしゃ', 'médico'),
  ('者', '学者', 'がくしゃ', 'académico / erudito'),
  ('者', '若者', 'わかもの', 'joven / juventud'),
  ('待', '待つ', 'まつ', 'esperar'),
  ('待', '期待', 'きたい', 'expectativa'),
  ('待', '招待', 'しょうたい', 'invitación'),
  ('持', '持つ', 'もつ', 'tener / sostener'),
  ('持', '気持ち', 'きもち', 'sentimiento'),
  ('持', '持参', 'じさん', 'llevar consigo'),
  ('動', '動く', 'うごく', 'moverse'),
  ('動', '運動', 'うんどう', 'ejercicio'),
  ('動', '動物園', 'どうぶつえん', 'zoológico'),
  ('始', '始まる', 'はじまる', 'comenzar'),
  ('始', '開始', 'かいし', 'inicio'),
  ('始', '始発', 'しはつ', 'primer tren del día'),
  ('暑', '暑い', 'あつい', 'caluroso'),
  ('暑', '暑さ', 'あつさ', 'calor'),
  ('暑', '蒸し暑い', 'むしあつい', 'bochornoso'),
  ('寒', '寒い', 'さむい', 'frío'),
  ('寒', '寒気', 'さむけ', 'escalofrío'),
  ('寒', '寒波', 'かんぱ', 'ola de frío'),
  ('味', '味', 'あじ', 'sabor'),
  ('味', '意味', 'いみ', 'significado'),
  ('味', '味方', 'みかた', 'aliado'),
  ('開', '開ける', 'あける', 'abrir'),
  ('開', '開く', 'ひらく', 'abrir(se)'),
  ('開', '公開', 'こうかい', 'apertura pública / estreno'),
  ('問', '問題', 'もんだい', 'problema'),
  ('問', '質問', 'しつもん', 'pregunta'),
  ('問', '疑問', 'ぎもん', 'duda'),
  ('運', '運ぶ', 'はこぶ', 'transportar'),
  ('運', '運転', 'うんてん', 'conducir'),
  ('運', '運命', 'うんめい', 'destino'),
  ('転', '転ぶ', 'ころぶ', 'caerse'),
  ('転', '自転車', 'じてんしゃ', 'bicicleta'),
  ('転', '転校', 'てんこう', 'cambio de escuela'),
  ('品', '商品', 'しょうひん', 'producto'),
  ('品', '品物', 'しなもの', 'artículo / mercancía'),
  ('品', '上品', 'じょうひん', 'elegante / refinado'),
  ('屋', '部屋', 'へや', 'habitación'),
  ('屋', '本屋', 'ほんや', 'librería'),
  ('屋', '屋根', 'やね', 'techo / tejado'),
  ('急', '急ぐ', 'いそぐ', 'apurarse'),
  ('急', '急行', 'きゅうこう', 'tren expreso'),
  ('急', '急に', 'きゅうに', 'repentinamente'),
  ('意', '意味', 'いみ', 'significado'),
  ('意', '注意', 'ちゅうい', 'cuidado / atención'),
  ('意', '意見', 'いけん', 'opinión'),
  ('悪', '悪い', 'わるい', 'malo'),
  ('悪', '悪口', 'わるぐち', 'insulto / mala palabra'),
  ('悪', '悪化', 'あっか', 'empeoramiento'),
  ('暗', '暗い', 'くらい', 'oscuro'),
  ('暗', '暗記', 'あんき', 'memorización'),
  ('暗', '暗号', 'あんごう', 'código / cifrado'),
  ('世', '世界', 'せかい', 'mundo'),
  ('世', '世紀', 'せいき', 'siglo'),
  ('世', '世代', 'せだい', 'generación'),
  ('界', '世界', 'せかい', 'mundo'),
  ('界', '業界', 'ぎょうかい', 'industria / sector'),
  ('界', '限界', 'げんかい', 'límite'),
  ('住', '住む', 'すむ', 'vivir / residir'),
  ('住', '住所', 'じゅうしょ', 'dirección postal'),
  ('住', '住宅', 'じゅうたく', 'vivienda / residencia'),
  ('洋', '洋服', 'ようふく', 'ropa occidental'),
  ('洋', '太平洋', 'たいへいよう', 'océano Pacífico'),
  ('洋', '東洋', 'とうよう', 'Oriente'),
  ('注', '注ぐ', 'そそぐ', 'verter'),
  ('注', '注意', 'ちゅうい', 'cuidado / atención'),
  ('注', '注文', 'ちゅうもん', 'pedido / orden'),
  ('死', '死ぬ', 'しぬ', 'morir'),
  ('死', '必死', 'ひっし', 'desesperado / a muerte'),
  ('死', '死亡', 'しぼう', 'muerte / fallecimiento'),
  ('漢', '漢字', 'かんじ', 'kanji'),
  ('漢', '漢方', 'かんぽう', 'medicina china tradicional'),
  ('漢', '漢文', 'かんぶん', 'chino clásico'),
  ('主', '主人', 'しゅじん', 'marido / dueño'),
  ('主', '主に', 'おもに', 'principalmente'),
  ('主', '主役', 'しゅやく', 'protagonista'),
  ('送', '送る', 'おくる', 'enviar'),
  ('送', '送料', 'そうりょう', 'costo de envío'),
  ('送', '放送', 'ほうそう', 'transmisión'),
  ('進', '進む', 'すすむ', 'avanzar'),
  ('進', '進行', 'しんこう', 'avance / progreso'),
  ('進', '進化', 'しんか', 'evolución'),
  ('去', '去る', 'さる', 'irse / partir'),
  ('去', '過去', 'かこ', 'pasado'),
  ('去', '去年', 'きょねん', 'año pasado'),
  ('集', '集める', 'あつめる', 'juntar / coleccionar'),
  ('集', '集合', 'しゅうごう', 'reunión / concentración'),
  ('集', '集中', 'しゅうちゅう', 'concentración'),
  ('起', '起きる', 'おきる', 'levantarse'),
  ('起', '起こる', 'おこる', 'ocurrir'),
  ('起', '起源', 'きげん', 'origen'),
  ('勉', '勉強', 'べんきょう', 'estudio'),
  ('勉', '勤勉', 'きんべん', 'diligente'),
  ('勉', '勉学', 'べんがく', 'estudios'),
  ('写', '写真', 'しゃしん', 'fotografía'),
  ('写', '写す', 'うつす', 'copiar / fotografiar'),
  ('写', '描写', 'びょうしゃ', 'descripción / representación'),
  ('真', '写真', 'しゃしん', 'fotografía'),
  ('真', '真実', 'しんじつ', 'verdad'),
  ('真', '真面目', 'まじめ', 'serio / responsable'),
  ('仕', '仕事', 'しごと', 'trabajo'),
  ('仕', '仕方', 'しかた', 'manera / forma'),
  ('仕', '仕上げ', 'しあげ', 'acabado / finalización'),
  ('事', '事', 'こと', 'cosa / asunto'),
  ('事', '大事', 'だいじ', 'importante'),
  ('事', '火事', 'かじ', 'incendio'),
  ('館', '図書館', 'としょかん', 'biblioteca'),
  ('館', '大使館', 'たいしかん', 'embajada'),
  ('館', '映画館', 'えいがかん', 'cine (sala)'),
  ('服', '服', 'ふく', 'ropa'),
  ('服', '洋服', 'ようふく', 'ropa occidental'),
  ('服', '制服', 'せいふく', 'uniforme'),
  ('院', '病院', 'びょういん', 'hospital'),
  ('院', '大学院', 'だいがくいん', 'escuela de posgrado'),
  ('院', '入院', 'にゅういん', 'hospitalización'),
  ('病', '病気', 'びょうき', 'enfermedad'),
  ('病', '病院', 'びょういん', 'hospital'),
  ('病', '病人', 'びょうにん', 'paciente'),
  ('医', '医者', 'いしゃ', 'médico'),
  ('医', '医学', 'いがく', 'medicina (ciencia)'),
  ('医', '医院', 'いいん', 'clínica'),
  ('使', '使う', 'つかう', 'usar'),
  ('使', '大使', 'たいし', 'embajador'),
  ('使', '天使', 'てんし', 'ángel'),
  ('旅', '旅行', 'りょこう', 'viaje'),
  ('旅', '旅館', 'りょかん', 'posada tradicional'),
  ('旅', '旅人', 'たびびと', 'viajero'),
  ('族', '家族', 'かぞく', 'familia'),
  ('族', '民族', 'みんぞく', 'etnia / pueblo'),
  ('族', '貴族', 'きぞく', 'nobleza'),
  ('所', '場所', 'ばしょ', 'lugar'),
  ('所', '台所', 'だいどころ', 'cocina'),
  ('所', '事務所', 'じむしょ', 'oficina'),
  ('乗', '乗る', 'のる', 'subirse / montar'),
  ('乗', '乗客', 'じょうきゃく', 'pasajero'),
  ('乗', '乗車', 'じょうしゃ', 'abordar un vehículo'),
  ('物', '物', 'もの', 'cosa / objeto'),
  ('物', '動物', 'どうぶつ', 'animal'),
  ('物', '荷物', 'にもつ', 'equipaje / paquete'),
  ('短', '短い', 'みじかい', 'corto'),
  ('短', '短所', 'たんしょ', 'defecto / punto débil'),
  ('短', '最短', 'さいたん', 'más corto'),
  ('員', '会社員', 'かいしゃいん', 'empleado de empresa'),
  ('員', '店員', 'てんいん', 'dependiente'),
  ('員', '会員', 'かいいん', 'miembro / socio'),
  ('着', '着る', 'きる', 'vestirse'),
  ('着', '到着', 'とうちゃく', 'llegada'),
  ('着', '着物', 'きもの', 'kimono'),
  ('終', '終わる', 'おわる', 'terminar'),
  ('終', '終電', 'しゅうでん', 'último tren'),
  ('終', '終点', 'しゅうてん', 'última parada'),
  ('軽', '軽い', 'かるい', 'ligero'),
  ('軽', '軽食', 'けいしょく', 'refrigerio'),
  ('軽', '手軽', 'てがる', 'fácil / práctico'),
  ('習', '習う', 'ならう', 'aprender'),
  ('習', '練習', 'れんしゅう', 'práctica'),
  ('習', '学習', 'がくしゅう', 'aprendizaje'),
  ('発', '出発', 'しゅっぱつ', 'salida / partida'),
  ('発', '発見', 'はっけん', 'descubrimiento'),
  ('発', '発表', 'はっぴょう', 'anuncio / presentación'),
  ('銀', '銀', 'ぎん', 'plata'),
  ('銀', '銀行', 'ぎんこう', 'banco'),
  ('銀', '銀色', 'ぎんいろ', 'color plateado'),
  ('代', '時代', 'じだい', 'era / época'),
  ('代', '代わり', 'かわり', 'reemplazo / sustituto'),
  ('代', '現代', 'げんだい', 'era moderna'),
  ('区', '区', 'く', 'distrito'),
  ('区', '地区', 'ちく', 'zona / área'),
  ('区', '区別', 'くべつ', 'distinción'),
  ('県', '県', 'けん', 'prefectura'),
  ('県', '県立', 'けんりつ', 'prefectural'),
  ('県', '県立', 'けんりつ', 'prefectural'),
  ('都', '京都', 'きょうと', 'Kioto'),
  ('都', '都市', 'とし', 'ciudad'),
  ('都', '都会', 'とかい', 'metrópolis'),
  ('題', '問題', 'もんだい', 'problema'),
  ('題', '題名', 'だいめい', 'título'),
  ('題', '話題', 'わだい', 'tema de conversación'),
  ('業', '授業', 'じゅぎょう', 'clase'),
  ('業', '工業', 'こうぎょう', 'industria'),
  ('業', '卒業', 'そつぎょう', 'graduación'),
  ('試', '試験', 'しけん', 'examen'),
  ('試', '試合', 'しあい', 'partido / competencia'),
  ('試', '試着', 'しちゃく', 'probarse ropa'),
  ('験', '試験', 'しけん', 'examen'),
  ('験', '経験', 'けいけん', 'experiencia'),
  ('験', '実験', 'じっけん', 'experimento'),
  ('説', '説明', 'せつめい', 'explicación'),
  ('説', '小説', 'しょうせつ', 'novela'),
  ('説', '演説', 'えんぜつ', 'discurso'),
  ('産', '産業', 'さんぎょう', 'industria'),
  ('産', '出産', 'しゅっさん', 'parto / nacimiento'),
  ('産', '生産', 'せいさん', 'producción'),
  ('飯', 'ご飯', 'ごはん', 'arroz / comida'),
  ('飯', '朝ご飯', 'あさごはん', 'desayuno'),
  ('飯', '夕飯', 'ゆうはん', 'cena'),
  ('無', '無理', 'むり', 'imposible'),
  ('無', '無料', 'むりょう', 'gratis'),
  ('無', '無視', 'むし', 'ignorar'),
  ('以', '以上', 'いじょう', 'más de / superior a'),
  ('以', '以下', 'いか', 'menos de / inferior a'),
  ('以', '以前', 'いぜん', 'antes / anteriormente'),
  ('英', '英語', 'えいご', 'idioma inglés'),
  ('英', '英国', 'えいこく', 'Reino Unido'),
  ('英', '英雄', 'えいゆう', 'héroe'),
  ('民', '国民', 'こくみん', 'ciudadano / pueblo'),
  ('民', '民主', 'みんしゅ', 'democracia'),
  ('民', '農民', 'のうみん', 'campesino'),
  ('借', '借りる', 'かりる', 'pedir prestado'),
  ('借', '借金', 'しゃっきん', 'deuda'),
  ('借', '借用', 'しゃくよう', 'préstamo formal'),
  ('便', '便利', 'べんり', 'conveniente'),
  ('便', '郵便', 'ゆうびん', 'correo postal'),
  ('便', '便所', 'べんじょ', 'baño / lavabo'),
  ('不', '不便', 'ふべん', 'inconveniente'),
  ('不', '不安', 'ふあん', 'inquietud / ansiedad'),
  ('不', '不思議', 'ふしぎ', 'misterioso / extraño'),
  ('好', '好き', 'すき', 'gustar'),
  ('好', '好物', 'こうぶつ', 'comida favorita'),
  ('好', '大好き', 'だいすき', 'gustar mucho'),
  ('働', '働く', 'はたらく', 'trabajar'),
  ('働', '労働', 'ろうどう', 'trabajo / labor'),
  ('働', '労働者', 'ろうどうしゃ', 'trabajador'),
  ('低', '低い', 'ひくい', 'bajo'),
  ('低', '最低', 'さいてい', 'mínimo / lo peor'),
  ('低', '低温', 'ていおん', 'baja temperatura'),
  ('菜', '野菜', 'やさい', 'verdura'),
  ('菜', '白菜', 'はくさい', 'repollo chino'),
  ('菜', '菜食', 'さいしょく', 'dieta vegetariana'),
  ('料', '料理', 'りょうり', 'cocina / plato'),
  ('料', '材料', 'ざいりょう', 'material / ingrediente'),
  ('料', '給料', 'きゅうりょう', 'salario'),
  ('特', '特別', 'とくべつ', 'especial'),
  ('特', '特に', 'とくに', 'especialmente'),
  ('特', '特急', 'とっきゅう', 'tren superexpreso'),
  ('別', '別', 'べつ', 'diferente / aparte'),
  ('別', '別れる', 'わかれる', 'separarse'),
  ('別', '別々', 'べつべつ', 'por separado'),
  ('堂', '食堂', 'しょくどう', 'comedor'),
  ('堂', '講堂', 'こうどう', 'auditorio'),
  ('堂', '本堂', 'ほんどう', 'salón principal de un templo'),
  ('貸', '貸す', 'かす', 'prestar'),
  ('貸', '貸し', 'かし', 'préstamo'),
  ('貸', '貸家', 'かしや', 'casa en alquiler'),
  ('私', '私', 'わたし', 'yo'),
  ('私', '私立', 'しりつ', 'privado (institución)'),
  ('私', '私鉄', 'してつ', 'ferrocarril privado'),
  ('洗', '洗う', 'あらう', 'lavar'),
  ('洗', '洗濯', 'せんたく', 'lavado de ropa'),
  ('洗', '洗面所', 'せんめんじょ', 'lavabo'),
  ('映', '映画', 'えいが', 'película'),
  ('映', '反映', 'はんえい', 'reflejo'),
  ('映', '上映', 'じょうえい', 'proyección de película'),
  ('研', '研究', 'けんきゅう', 'investigación'),
  ('研', '研修', 'けんしゅう', 'entrenamiento / capacitación'),
  ('研', '研究所', 'けんきゅうじょ', 'instituto de investigación'),
  ('究', '研究', 'けんきゅう', 'investigación'),
  ('究', '究極', 'きゅうきょく', 'último / extremo'),
  ('究', '探究', 'たんきゅう', 'búsqueda / investigación'),
  ('建', '建てる', 'たてる', 'construir'),
  ('建', '建物', 'たてもの', 'edificio'),
  ('建', '建築', 'けんちく', 'arquitectura'),
  ('有', '有名', 'ゆうめい', 'famoso'),
  ('有', '有料', 'ゆうりょう', 'de pago (no gratis)'),
  ('有', '有効', 'ゆうこう', 'válido'),
  ('度', '一度', 'いちど', 'una vez'),
  ('度', '温度', 'おんど', 'temperatura'),
  ('度', '態度', 'たいど', 'actitud'),
  ('質', '質問', 'しつもん', 'pregunta'),
  ('質', '品質', 'ひんしつ', 'calidad'),
  ('質', '性質', 'せいしつ', 'naturaleza / carácter')
) AS v(caracter, palabra, furigana, traduccion)
JOIN kanji k ON k.caracter = v.caracter;
